### ISSUE TITLE
8muses no download

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#106]
manga-py version `1.3.24`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://www.8muses.com/comics/album/Girls-of-Skyrim
~~~
~~~
Before content
~~~
Nothing is downloaded.

Tried with `https://www.8muses.com/comics/album/Girls-of-Skyrim/Girls-of-Skyrim-1`, same result.
Tried with random comics of the web and same result (Single comics, numbered, collections, ...).

**Comment by 1271** [comment]
I will check it. Thank you

**Comment by 1271** [comment]
Support for 8muses will be temporarily closed.
Now I do not have time to decipher this.
Most likely, one day it will be done.

You can see for yourself what they did.
view-source: https: //www.8muses.com/comics/picture/Girls-of-Skyrim/Girls-of-Skyrim-8/1

**Comment by gromenauer** [comment]
Still pending in 1.7.2

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://www.8muses.com/comics/album/Girls-of-Skyrim`

**Comment by 1271** [comment]
yes I remember
As soon as there is a lot of free time, I will try to solve it.

**Comment by 1271** [comment]
Site closed
