### ISSUE TITLE
mangazuki.me, mangazuki.online & mangazuki.info

### ISSUE THREAD

**Issue by worstgamedev** [manga-py/manga-py#192]
# Request to add a site

Description | Just hoping to add these sites cuz manhwahentai got nuked and have no other manhwa sites to download from.
---|---
Url to add | https://mangazuki.me/ & https://mangazuki.info/ & https://www.mangazuki.online/

**Comment by 1271** [comment]
I removed the manhwahentai from the list of available

---

Oh... What a horrible sites -_-
The person who made them must burn in hell
My browser suffered all the time :-(

And `mangazuki.online` generally opened the main page, and then the site "down" and that's it. Now all the time gives error 503

Test result from different countries:
https://ping-admin.ru/free_test/result/1561801917vx0b321oa0g855ue9hi7m.html

So it goes...

**Comment by 1271** [comment]
Oh! `mangazuki.online `works
I will try to add support soon

**Comment by gromenauer** [comment]
Works OK (`mangazuki.online`)

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.2.1
URL | `https://mangazuki.me/manga/29-sai-dokushin-wa-isekai-de-jiyuu-ni-ikita/`

**Comment by 1271** [comment]
I close it. If you're still having trouble, create a new issue.

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.2.3
URL | `https://www.mangazuki.online/manga/29-sai-dokushin-wa-isekai-de-jiyuu-ni-ikita/`
URL | `https://www.mangazuki.info/manga/29-sai-dokushin-wa-isekai-de-jiyuu-ni-ikita/`
