### ISSUE TITLE
Bug: chapter names in merakiscans.com provider

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#193]
# Bug report
Environment (please complete the following information):

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.0
URL | `https://merakiscans.com/details/my-wife-is-a-demon-queen/`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  https://merakiscans.com/details/my-wife-is-a-demon-queen/ \
  --simulate --print-json \
  | grep path 
~~~

#### Additional context
All file names are the same.
~~~
      "path": "/home/alicia/Descargas/Pendiente/Manga/my-wife-is-a-demon-queen/vol_0my-wife-is-a-demon-queen.cbz",
      "path": "/home/alicia/Descargas/Pendiente/Manga/my-wife-is-a-demon-queen/vol_0my-wife-is-a-demon-queen.cbz",
      "path": "/home/alicia/Descargas/Pendiente/Manga/my-wife-is-a-demon-queen/vol_0my-wife-is-a-demon-queen.cbz",
...
~~~

Another problem is that `https://merakiscans.com/details/my-wife-is-a-demon-queen/` in the web redirects to  `https://merakiscans.com/manga/my-wife-is-a-demon-queen/` 

My first attempt was:
~~~
manga-py https://merakiscans.com/manga/my-wife-is-a-demon-queen
...
    raise AttributeError('Provider not found')
~~~
Only researching in previous issues could I attempt with `.../details/...`

**Comment by 1271** [comment]
Oh. It is not difficult. Thanks for the issue

**Comment by 1271** [comment]
Patch done )

**Comment by gromenauer** [comment]
Works for me :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://merakiscans.com/manga/my-wife-is-a-demon-queen/`
