### ISSUE TITLE
Only one chapter is downloaded

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#195]
# Bug report

Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.0
URL | `https://mangakakalot.com/manga/saihate_no_paladin`
URL | `https://mangadex.org/title/39036/that-inferior-knight-lv-999`
URL | `https://bato.to/series/68102`

#### To Reproduce:
~~~ bash
manga-py https://mangakakalot.com/manga/saihate_no_paladin
manga-py https://mangadex.org/title/39036/that-inferior-knight-lv-999
manga-py https://bato.to/series/68102
~~~
Only one chapter per url is downloaded

#### Additional context

With Manga-py version 1.7.2 it worked, commit 192e59df0e97f51e815f326d9d182b67ea34e993 seems where the bug is.

**Comment by 1271** [comment]
Ohh.. Sorry.

Fixed

**Comment by gromenauer** [comment]
Works OK in 1.8.1 :+1: 

Component | Value
---|---
OS | Debian GNU/Linux 8 (jessie)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Manga-py version | 1.8.1
URL | `https://mangakakalot.com/manga/saihate_no_paladin`
URL | `https://mangadex.org/title/39036/that-inferior-knight-lv-999`
URL | `https://bato.to/series/68102`
