### ISSUE TITLE
Add "online" viewing

### ISSUE THREAD

**Issue by Baitinq** [manga-py/manga-py#200]
It would be incredible if manga-dl could display manga from a website like so `manga-dl --online 'NAME_OF_MANGA_SERIES`. This could be useful if you wanted to just read a manga series without wasting hard drive space as well as not having to see all those annoying ads that you find on some manga websites. This feature could open the manga in a pdf viewer like zathura.

**Comment by 1271** [comment]
Hi.
Unfortunately, to open a pdf file, you first need to create it.
And for this you need to download all the images to disk.

manga-py thought of exactly as a means of something that would help you read manga on your phone, without thinking about your mobile traffic.

I understand what you mean, but I am not sure that it is possible to implement it at all.

**Comment by Baitinq** [comment]
Cant the images be streamed? I dont have a lot of technical knowledge on this aspect. An example of this could be mpv (the music player), idk how it does it but it can play youtube videos without downloading them. Btw i love your script anyways

**Comment by 1271** [comment]
Thank.

At the expense of the pipe ... I'm not sure that this can be implemented (I don’t know of any programs for viewing pdf that can read from the standard output)
As for mpv, there’s a slightly different story. He just knows how to open video by url, if my memory serves me (he uses youtube-dl to get links, like)
Technically, manga-py can give links to images, but it often does not make sense (see #184)

**Comment by 1271** [comment]
Some sites encrypt their images, some do not allow receiving images via direct links.
On some sites, the link lifetime is a few seconds :-)

**Comment by 1271** [comment]
P.S.
I read #201
Installing something as root is not a good idea.
Better use setting for user or venv (https://docs.python.org/3/library/venv.html)


--- 

P.P.S.

If you experience problems with free space, you can use the -s (skip) and -c (count) parameters

For example:
`manga-py -s 3 -c 2 http://manga/here`

This downloads chapter 4 and 5

See full help:
`manga-py --help`

**Comment by Baitinq** [comment]
Thank you so much for the extensive help. I reinstalled the script without root and it worked perfectly fine. Btw would you mind me posting a PKGBUILD of this program to the AUR?

**Comment by 1271** [comment]
No problems.

Thank you for using it.

**Comment by 1271** [comment]
I will close it. If you still have questions, feel free to create a new issue.
