### ISSUE TITLE
No #!/usr/bin/python3

### ISSUE THREAD

**Issue by Baitinq** [manga-py/manga-py#201]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Arch linux
Python version | 3.7.3-2
Manga-py version | Latest
URL | http://manga/url/here

#### To Reproduce:
1. Run manga-dl from the terminal

When I run manga-dl from the terminal it doesnt work, as the file /usr/bin/manga-dl doesnt have #!/usr/bin/python3 at the top. For the program to work I have to run `python /usr/bin/manga-dl`.

My /usr/bin/manga-dl file.
`"""
Copyright 2015-2017 Hermann Krumrey

This file is part of manga-dl.

manga-dl is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

manga-dl is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with manga-dl.  If not, see <http://www.gnu.org/licenses/>.
"""

from manga_dl.main import main

if __name__ == "__main__":
    main()
`

Btw I installed this program by doing `python setup.py install`

**Comment by 1271** [comment]
Sorry, you confused the project.

Please try:

pip install manga-py
