### ISSUE TITLE
Error installing manga-dl

### ISSUE THREAD

**Issue by Baitinq** [manga-py/manga-py#202]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Arch linux
Python version | 3.7.3-2
Manga-py version | Latest
URL | http://manga/url/here

#### To Reproduce:
1. Install manga-dl by issuing the command `python setup.py install`

I get this error when installing manga-dl

`Finished processing dependencies for manga-py==1.8.2.2
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/baitinq/manga-dl-git/src/manga-dl/manga_py/__init__.py", line 34, in before_shutdown
    temp_dir = get_temp_path()
NameError: name 'get_temp_path' is not defined
`

**Comment by 1271** [comment]
Please, try it:

`pip install manga-py`

:-)
