### ISSUE TITLE
Request to add a site: leviatanscans

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#203]
# Request to add a site

Description | Data
---|---
Url to add | `https://leviatanscans.com/comics/157887-a-returners-magic-should-be-special`

**Comment by 1271** [comment]
Oh.. Done =)
https://github.com/yuru-yuri/manga-py/commit/3da8e21e71ff3478ef1d1eddfdfc586202ec349e

**Comment by gromenauer** [comment]
Works OK :+1: 

Should the file format be `vol_070-0.cbz`? (Now is `vol_001-70.cbz`)

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.3.1
URL | `https://leviatanscans.com/comics/157887-a-returners-magic-should-be-special`

**Comment by 1271** [comment]
> Should the file format be vol_070-0.cbz? (Now is vol_001-70.cbz)

No. That's right. This is how numbers are stored on the site. I could not find an example where the chapters would be stored differently, so I decided to leave it that way.
If there are errors, fix it :-)

**Comment by gromenauer** [comment]
Good enough :innocent:
