### ISSUE TITLE
Site down: atelierdunoir

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#204]
Seems gone to mangadex and googledrive (See https://atelierdunoir.wordpress.com/)

Description | Data
---|---
Url down | http://www.atelierdunoir.info/

**Comment by 1271** [comment]
Thank. I will remove the site from the supported.

As for the new location. Sorry, but I have no plans to add support for google drive
This is excessive complexity.
Perhaps one day I will return to this question, but not now

**Comment by 1271** [comment]
Thanks. I will remove the site from the supported.

As for the new location. Sorry, but I have no plans to add support for google drive
This is excessive complexity.
Perhaps one day I will return to this question, but not now

**Comment by 1271** [comment]
Removed
