### ISSUE TITLE
mangahub.ru not worked

### ISSUE THREAD

**Issue by 1271** [manga-py/manga-py#206]
Example:
https://mangahub.ru/tanaka_kun_is_always_listless

**Comment by gromenauer** [comment]
Works :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.3.1
URL | `-https://mangahub.ru/tanaka_kun_is_always_listless`
