### ISSUE TITLE
[Japscan.to] Captcha error

### ISSUE THREAD

**Issue by sam5558** [manga-py/manga-py#208]
Hello, 
great piece of code you have there.
When trying to download a random manga from Japscan, i'm faced with with a captcha error. Is it just me or is it a global issue ?

```bash
ERROR:root:"https://www.japscan.to/manga/perfect-world/" returned an error. Could not collect tokens.
CF error! Captcha
```

**Comment by sam5558** [comment]
Looks like it's related to CloudFlare :( 

```
It's CloudFlare issue, They update JS Challenges again.

Everything with CF can cause a 503 error.
```

I've checked on Tachiyomi app (basically an android app that scraps from various websites), as they manage japscan also and it works like a charm (on github it looks like they updated their code for this https://github.com/inorichi/tachiyomi/commit/7551941ef22b6dda64f532e89ade19a8148cad13) 

Any help ?
Thank you

**Comment by 1271** [comment]
Hello! A third-party library is used to solve the CloudFlare problem.
Please wait while they release the update.
Thanks for the insight.
(https://github.com/venomous/cloudscraper)

You can also try updating this library forcibly:
`pip install -U cloudscraper`

Check version:
`pip show cloudscraper`

Actual version:
<img src="https://badge.fury.io/py/cloudscraper.svg" alt="1.1.39">

**Comment by sam5558** [comment]
I've updated the cloudscraper version to 1.1.39, now the command line returns .... nothing :D
Anyway i'll wait for your update, thanks for your help !

**Comment by 1271** [comment]
> returns .... nothing

In the near future I will update the provider.
(there have been changes on the site)

Now it is already working and ready for release, but I need to fix some more things in other places.

Thank you for your patience.

**Comment by 1271** [comment]
hi @sam5558 
Tell me, is there a problem now?

**Comment by sam5558** [comment]
Hello @1271 ,
After updating to the latest version of manga-py (1.8.3.1), it's now working again.
Thank you so much :+1:

**Comment by 1271** [comment]
Thanks for your support.
