### ISSUE TITLE
Silent error in redirection

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#210]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.2.3
URL | :warning:  `https://mangakakalot.com/manga/bq919100`
URL | :+1: `https://manganelo.com/manga/bq919100`

#### To Reproduce:
~~~ bash
# Redirected address to manganelo.com
manga-py https://mangakakalot.com/manga/bq919100 
# Bad address
manga-py https://mangakakalot.com/manga/bq919
~~~

#### Additional context
It should warn that this is not a valid page, return an error or raise an exception.
With no output it seems that no new comics arrived, but what happened is that the page got redirected or is a broken link.

**Comment by 1271** [comment]
I'll think about how to do it. :-)
Thank.

**Comment by 1271** [comment]
A warning will now appear if it was not possible to get a list of chapters

**Comment by gromenauer** [comment]
Works  OK :+1: 
See if you like the enhancement in #212 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.3.1
URL | `https://mangakakalot.com/manga/bq919`
