### ISSUE TITLE
Bug in provider mangahere.cc

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#213]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.3.1
URL | `http://www.mangahere.cc/manga/hagure_yuusha_no_kichiku_bigaku`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages \
  --no-webp --show-current-chapter-info \
  --destination ./Manga/ \
  http://www.mangahere.cc/manga/hagure_yuusha_no_kichiku_bigaku
~~~

#### Additional context
Output:
~~~
2019-08-22 19:48:52.000 | WARNING  | manga_py.base_classes.base:_prepare_chapters:131 - Chapters list empty. Check http://www.mangahere.cc/manga/hagure_yuusha_no_kichiku_bigaku
~~~

But the content is there.

**Comment by 1271** [comment]
also need add `isAdult=1` cookie

example: http://www.mangahere.cc/manga/azumi/

**Comment by 1271** [comment]
Oh (
They introduced obfuscation.
Have to completely rewrite the provider. I'll do it tomorrow.

P.S.

see: `http://www.mangahere.cc/manga/<name>/<chapter>/chapterfun.ashx?<params>`

**Comment by 1271** [comment]
Ok. Done

`
pip install manga-py==1.8.4rc3
`

After confirming viz.com will be released.
  Now you can use the release candidate version. She is fully functional.

**Comment by 1271** [comment]
In the near future, the project will move here:
https://github.com/manga-py

I hope this will look logical.

**Comment by gromenauer** [comment]
Works OK :+1: in `1.8.4-rc.3`

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.4-rc.3
URL | `http://www.mangahere.cc/manga/hagure_yuusha_no_kichiku_bigaku`

**Comment by gromenauer** [comment]
Moving the repository to https://github.com/manga-py seems a good move to me. (Best moving than cloning, retains issues, ...).
