### ISSUE TITLE
Possibility to deploy as part of open source Android and iOS app?

### ISSUE THREAD

**Issue by rookiegrammer** [manga-py/manga-py#214]
Since python is runnable on mobile devices, is it possible to use this as part of an "Open Source" mobile manga downloader app like Tachiyomi?

I've also found this:
https://github.com/JaneaSystems/nodejs-mobile

**Comment by rookiegrammer** [comment]
Maybe we should wait for feature #40 to be done though... 😞

**Comment by gromenauer** [comment]
@rookiegrammer you could try running it with:
* pyodide https://github.com/iodide-project/pyodide
* brython https://github.com/brython-dev/brython

**Comment by 1271** [comment]
> Maybe we should wait for feature #40 to be done though... 

You can use it now.

All endpoints can be seen here:
https://github.com/yuru-yuri/manga-py/blob/stable_1.x/manga_py/cli/__init__.py
also see https://github.com/yuru-yuri/manga-py/blob/stable_1.x/manga_py/cli/args.py

```python

# I will try to sign in more detail.

from manga_py.parser import Parser

# main class (you will have your own)
class YoutAwesomeClass:
    args = None # is just a dict with arguments (filled below. You can implement your implementation. The main thing is to have all keys possible)
    parser = None # the found parser gets here (see below)
    _info = None # use the Info class from manga-py or overload the Info class from manga-py
    __progress_bar = None # you can write your function and pass it as a callback parameter. The function will be called after each downloaded file (see example below)

    def start (self):
        self.parser = Parser(args)
        try:
            self.parser.init_provider (
                progress = self.progress,
                log = self.print,
                quest = self.quest,
                quest_password = self.quest_password,
                info = self._info,
            )
        except AttributeError as e:
            raise e
        self.parser.start ()  # provider main method

    def progress (self, items_count: int, current_item: int, re_init: bool = False): # the same progress function. re_init = True means "next chapter"
        # simple progress
        pass

    def print (self, text, ** kwargs):
        # Not used everywhere. Better reload global print method
        # I will fix it one day ...
        pass

    def quest (self, variants: enumerate, title: str, select_type = 0): # 0 = single, 1 = multiple / Used when some answers are required from the user
        print(' Question ')
        return 'Answer'

    def quest_password (self, title): # used to ask user password
        return 'password'

```

**Comment by 1271** [comment]
This way you can use manga-py in any of your applications, be it iOS, Android or Web

**Comment by gromenauer** [comment]
Suggestion: Add a `examples/embeeded.py` file with this source code (https://github.com/yuru-yuri/manga-py/issues/214#issuecomment-524567070) to the project.

**Comment by 1271** [comment]
No problem =)

**Comment by rookiegrammer** [comment]
I’ll try to look into this :). BTW @1271 how could the Node JS requirement of the app be brought from NodeJS to NodeJS-mobile or can Cloudflare issues be handled manually?

**Comment by 1271** [comment]
@rookiegrammer
You can look towards Termux.
It implements a package system, as in the "big" linux. Including nodejs.
Or, you can exclude sites with a nodejs requirement from support.
Or, you can launch a user’s browser with the desired site, collect cookies and transfer them to manga-py, along with the browser version. This is the best option, though it requires minor modifications. )

**Comment by 1271** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
