### ISSUE TITLE
readcomiconline.to, readcomicsonlie.ru not working

### ISSUE THREAD

**Issue by phanirithvij** [manga-py/manga-py#219]
# Bug report
Environment (please complete the following information):

**Docker image of manga-py**

Description | Data
---|---
OS | Windows 10 (docker image of manga-py)
Python version | 3.6.8
Pip version | 19.1.1
Manga-py version | 1.7.0
Node Js version | v12.4.0
URL | https://readcomicsonline.ru/comic/the-batman-who-laughs-2018, https://readcomiconline.to/Comic/The-Batman-Who-Laughs

#### To Reproduce:
1. `docker pull mangadl/manga-py && docker run -it mangadl/manga-py`
2. manga-py "https://readcomiconline.to/Comic/The-Batman-Who-Laughs"
3. No output doesn't download

With the other URL

1. manga-py "https://readcomicsonline.ru/comic/the-batman-who-laughs-2018"
2. Raises 
```python
 File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 35, in init_provider
    raise AttributeError('Provider not found')
```

#### Additional context
1. Both the URLs are in the list of providers.
2. I'm guessing the docker file wasn't updated recently?

**Comment by phanirithvij** [comment]
Other sites are working like `manga-py "https://kissmanga.com/Manga/The-Ghostly-Doctor"` etc

**Comment by phanirithvij** [comment]
And how do I copy the files downloaded in the docker to my filesystem?

**Comment by phanirithvij** [comment]
What do you think @1271

**Comment by 1271** [comment]
Hmmm... I don't see this error on my pc

![image](https://user-images.githubusercontent.com/1452243/64288854-c714f300-cf6b-11e9-8669-15e3c28c89d9.png)

Both addresses work well.

I will check it in the morning on my working PC

Thanks for reporting the problem.

**Comment by 1271** [comment]
> I'm guessing the docker file wasn't updated recently?

The docker file does not require updating (on server side). He always installs the latest version of manga-py when building.


```bash
docker rm mangadl/manga-py --force && docker pull mangadl/manga-py
```

Although usually enough to check for team updates:
`docker pull mangadl/manga-py`

**Comment by phanirithvij** [comment]
This is working for me for both URLs.

```shell
python manga.py "<url>"
```
I just cloned the repo and tried it.

But the docker container has the above issues.

**Comment by phanirithvij** [comment]
Oh, the version of manga-py in the docker image is `1.7.0` but not the latest `1.8.4`.
But it shouldn't be the case as I pulled it just a few (10) hours ago

**Comment by 1271** [comment]
Hmm ... you're right.
Today I will repair the docker)

@phanirithvij try it as temporary solved:

```bash
docker run -it mangadl/manga-py:1.8.4
```

**Comment by gromenauer** [comment]
Tried it without docker:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.4
URL | `https://readcomicsonline.ru/comic/the-batman-who-laughs-2018` :+1: 
URL | `https://readcomiconline.to/Comic/The-Batman-Who-Laughs` :bug: 

`https://readcomiconline.to/Comic/The-Batman-Who-Laughs` execution:

~~~ bash
pipenv run manga-py \
  --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
  --destination Manga/ -c 2 \
  https://readcomiconline.to/Comic/The-Batman-Who-Laughs

2019-09-05 16:12:42.033 | WARNING  | manga_py.base_classes.base:_prepare_chapters:130
- Chapters list empty. Check https://readcomiconline.to/Comic/The-Batman-Who-Laughs
~~~

**Comment by 1271** [comment]
@gromenauer 
Can you try downloading this?
I can not repeat this error.

Thank!

**Comment by gromenauer** [comment]
Tried again => `Chapters list empty`
Open `https://readcomiconline.to/Comic/The-Batman-Who-Laughs` in Firefox, seems OK.
Tried again => Downloads OK.
Maybe it marks the IP as "human" if you open it with a browser... :confused:

**Comment by 1271** [comment]
![sad](https://user-images.githubusercontent.com/1452243/64417355-9040f900-d0a1-11e9-9dfc-2de754b14813.png)
I will need your help in this case, because it works for me (checked docker, pip and just running the script)
In the evening I will make changes to the provider. It will be necessary to send the archive that he will create. Thank.

**Comment by gromenauer** [comment]
Tried again => Downloads OK.
Seems a Heisenbug, when you see the page the bug disappears.

**Comment by 1271** [comment]
I suspect that the site is sometimes "sick" 😂

**Comment by 1271** [comment]
I close it. If you still have questions, please create a new issue.
