### ISSUE TITLE
[mangastream.site] only download the first 3 images for each volume

### ISSUE THREAD

**Issue by aleifuu** [manga-py/manga-py#221]
when trying to download yakitate off from mangastream.site using the following command 

manga-py https://mangareader.site/manga/yakitate-japan_115 --max-volumes 1

unzip vol_001.zip 
Archive:  vol_001.zip
  inflating: 001_2.jpeg              
  inflating: 000_1.jpeg              
  inflating: 002_3.jpeg              
  inflating: info.txt                

I can download sucessfully from other url, for example manga99.com so i think this is probably site-specific issue

**Comment by 1271** [comment]
Hello. Does it happen every time?
I understand that there are no errors in the console?

Please attach the downloaded archive to your answer. thank

**Comment by aleifuu** [comment]
```
manga-py https://mangareader.site/manga/yakitate-japan_115 --max-volumes 1
100% (3 of 3) |################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00

```
Here's the downloaded archive
[vol_002.zip](https://github.com/manga-py/manga-py/files/3593419/vol_002.zip)


I can use manga-py with other sites. Just notice this problem with mangareader.site

Cheers

**Comment by 1271** [comment]
Ohh... 
I did not understand at first. Thank you for your comment.

**Comment by 1271** [comment]
Done.

Please, update manga-py:

`pip3 install manga-py==1.8.5rc2`

**Comment by aleifuu** [comment]
Ok. this is slightly out of scope, but hopefully someone can give me pointer what keyword to look or search etc 

Can't try `pip install manga-py=1.8.5rc2` yet

Since I originally installed manga-py using `pip3 install manga-py`

Suddenly this morning, I could no longer locate the executable manga-py. Just super weird. Try to install it back again using the same command `pip3 install manga-py` and it generates Segmentation Fault

Same issue was raised by one of member here but it had workaround with using docker, i guess it hasn't resolved the issue with Segmentation Fault. I can't use / run docker at the moment since I'm running my Linux under chroot ( via crouton in a Chromebook ) 

Been able to download manga nicely these few days until this morning happens. Aaargh. Can't wait to resume again

My question is we can actually use pip3 to install manga-py right ? 
my pip3 version is 

```
pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

**Comment by aleifuu** [comment]
By the way 

`
odroid@odroid:/home/pi$ pip3 install manga-py=1.8.5rc2
Invalid requirement: 'manga-py=1.8.5rc2'
= is not a valid operator. Did you mean == ?
`

So tried `pip3 install manga-py==1.8.5rc2` and it generates Segmentation Fault 


... maybe it doesn't work /w python 3.6 ?

**Comment by 1271** [comment]
Ohh...
Of course there are 2 signs needed = (I corrected my comment above)

>... maybe it doesn't work /w python 3.6 ?

Not. Each release is tested on python version 3.5 / 3.6 / 3.7

Please show error (screen or log).
I tested it on a blank PC and it works well.
![изображение](https://user-images.githubusercontent.com/1452243/64766543-d1785380-d54e-11e9-94de-73a19202c0de.png)

Travis-ci builds: https://travis-ci.org/manga-py/manga-py/builds/583827123

> My question is we can actually use pip3 to install manga-py right ?

Yes. Right.

**Comment by 1271** [comment]
As you see, i use python 3.6 too
![изображение](https://user-images.githubusercontent.com/1452243/64767758-f4a40280-d550-11e9-88c2-f4eac324c834.png)

**Comment by aleifuu** [comment]
*** Error compiling '/tmp/pip-build-man100bh/js2py/js2py/internals/speed.py'...
    File "/tmp/pip-build-man100bh/js2py/js2py/internals/speed.py", line 50
      print timeit(
                 ^
  SyntaxError: invalid syntax
  
  *** Error compiling '/tmp/pip-build-man100bh/js2py/js2py/test_internals.py'...
    File "/tmp/pip-build-man100bh/js2py/js2py/test_internals.py", line 9
      print seval.eval_js_vm(x)
                ^
  SyntaxError: invalid syntax
  






  changing mode of /home/pi/.local/bin/manga-py to 755
Segmentation fault


Something like that. It looks like internal (my) pip3 problem

**Comment by 1271** [comment]
Please, try it:

```bash
pip3 install Js2Py
pip3 install pyexecjs
pip3 install manga-py==1.8.5rc2
```

**Comment by 1271** [comment]
The problem is that the composition of the packages has not changed. Everything should work fine :-(

**Comment by aleifuu** [comment]
*** Error compiling '/tmp/pip-build-6am0lq5t/js2py/js2py/internals/speed.py'...
    File "/tmp/pip-build-6am0lq5t/js2py/js2py/internals/speed.py", line 50
      print timeit(
                 ^
  SyntaxError: invalid syntax
  
  *** Error compiling '/tmp/pip-build-6am0lq5t/js2py/js2py/test_internals.py'...
    File "/tmp/pip-build-6am0lq5t/js2py/js2py/test_internals.py", line 9
      print seval.eval_js_vm(x)
                ^
  SyntaxError: invalid syntax
  




  changing mode of /home/pi/.local/bin/chardetect to 755










  changing mode of /home/pi/.local/bin/manga-py to 755
Segmentation fault



Pretty much same result =(

**Comment by 1271** [comment]
Is this an error installing manga-py ??
Hmmm ...

O! I have an idea!

Try it:
```bash
python3 -m venv venv
. venv/bin/activate
pip install manga-py==1.8.5rc2  # not pip3 here!
```

**Comment by 1271** [comment]
> Pretty much same result =(

By the way.
`pip3 install Js2Py`
Did this command work correctly for you?

**Comment by aleifuu** [comment]
> pip3 install Js2Py

pip3 install Js2Py
Collecting Js2Py
Collecting tzlocal>=1.2 (from Js2Py)
  Using cached https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting pyjsparser>=2.5.1 (from Js2Py)
Collecting six>=1.10 (from Js2Py)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pytz (from tzlocal>=1.2->Js2Py)
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Installing collected packages: pytz, tzlocal, pyjsparser, six, Js2Py
Successfully installed Js2Py-0.66 pyjsparser-2.7.1 pytz-2019.2 six-1.12.0 tzlocal-2.0.0

Yes it seems It's installed successfully

**Comment by 1271** [comment]
Ok.

`pip3 install pyexecjs` ?


\\ installation of one package should not cause the reinstallation of another (if it was already installed earlier and the version has not changed)

**Comment by aleifuu** [comment]
Yes

> pip3 install pyexecjs

It also a success install, so im totally confused

Im not really a big python user, but hey someone needs to slay these
multi-verse python 2, 2.7, 3.0++ for good. And when i meant slay is
simplified the whole diversification already

As a note, I manage to do download manga-py.tar.gz ( version 1.8.4 ) and
manage to install using python3 setup.py install on the extracted folder

Can run and download manga on home folder, but other problem occurs that is
seemingly manga-py can't save to mounted network disk where I previously
set it to

**Comment by aleifuu** [comment]
And I'm not sure if it is permission problem

When you execute the command on the mounted disk

/mnt/network-disk $ manga-py url

/mnt/network-disk $

It will just generate a new blank line and return to command shell prompt

**Comment by 1271** [comment]
Oh .. I really do not recommend executing any commands from the root user.
This is really not good.

Please try to execute the commands above (duplicated):
```bash
python3 -m venv venv
.  venv/bin/activate  # Exactly. With a dot at the beginning
pip install manga-py==1.8.5rc2  # not pip3 here!
```

As for network drives, I have not tested this. Network drives always give a delay. In addition, sometimes there may be problems with creating / deleting files.

**Comment by aleifuu** [comment]
Ah no, the notation '#' in my last message doesn't mean I executed as root
user

Sorry If I confused you. It's just a random notation. I happen to pick #
lol

**Comment by aleifuu** [comment]
(venv) pi@odroid:~$ manga-py --version
1.8.5-rc.2

it works in venv environment

**Comment by 1271** [comment]
Yey! =)
Cool!

Using venv anytime, anywhere is cool, actually.
Although it would be great to deal with your problem. But I can not say why it does not work in a global environment.

**Comment by aleifuu** [comment]
> It will just generate a new blank line and return to command shell prompt
> /mnt/network-disk $ manga-py url 
> 
> /mnt/network-disk $ 

Btw the mysterious blank line, I figured out it means no more chapter available to download (duh!) ... maybe a good idea to spit out some messages rather than just blank line (IMHO) 

So it wasn't so much permission problem or other problem with my mounted disk connection

**Comment by 1271** [comment]
> no more chapter available to download

Hmm.
An empty line will be displayed only if you downloaded everything that is possible, yes.
If manga-py cannot find the list of chapters, an error will be displayed.

**Comment by aleifuu** [comment]
> An empty line will be displayed only if you downloaded everything that is possible, yes.

empty line also equates no response and sometimes people ( well, at least I did ! ) thought something is wrong since it looks like it's just not doing anything 

having a response like 'no new chapters available to download' maybe better 

just my 2cents

cheers,

**Comment by 1271** [comment]
I'll think about it, thanks.

If your problem is resolved, I would ask you to close the issue.
If you still have questions, feel free to.

**Comment by aleifuu** [comment]
Ok. please do close it 

This rc version resolves the initial bug question

(venv) pi@odroid:~$ manga-py https://mangareader.site/manga/yakitate-japan_115 --max-volumes 1
100% (45 of 45) |##############################################################################| Elapsed Time: 0:00:05 Time:  0:00:05
