### ISSUE TITLE
If manga-py does not detect new chapters, display a message about this.

### ISSUE THREAD

**Issue by 1271** [manga-py/manga-py#222]
https://github.com/manga-py/manga-py/issues/221#issuecomment-530840745

**Comment by gromenauer** [comment]
Could you add a `--quiet` flag parameter for disable this. https://github.com/gromenauer/manga_py_update works better if nothing is displayed when no new chapter is detected.

**Comment by 1271** [comment]
No problems. I'll do it in the next update.

**Comment by gromenauer** [comment]
`--quiet` prints `Not detect new chapters` anyway.

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.2
URL | `https://hiperdex.com/manga/the-great-mage-returns-after-4000-years/`

~~~ bash          
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga \
    --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
    --quiet \
    https://hiperdex.com/manga/the-great-mage-returns-after-4000-years/

Not detect new chapters
~~~

I'm not English native, but `Not detect new chapters` sounds off to me, may be it is `No new chapters are detected` (I recommend to have a English reviewer anyway).

**Comment by 1271** [comment]
Unfortunately me too.
But yes, "No new chapters are detected" sounds good.

**Comment by 1271** [comment]
Oh. Fixed. Thanks you

**Comment by 1271** [comment]
P.P.S. cloudflare protected sites are broken now.
see VeNoMouS/cloudscraper/issues/209

**Comment by gromenauer** [comment]
Oops Solved long ago
