### ISSUE TITLE
Recaptcha Issue

### ISSUE THREAD

**Issue by david-eve-za** [manga-py/manga-py#223]
# Bug report
Environment (please complete the following information):

Description | Data
ERROR:root:"https://tmofans.com/library/manga/16660/Hajimete-no-Gal" returned an error. Could not collect tokens.
CF error! Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
2019-09-26 03:59:37.124 | WARNING  | manga_py.base_classes.base:_prepare_chapters:130 - Chapters list empty. Check https://tmofans.com/library/manga/16660/Hajimete-no-Gal
OS | Ubuntu 18.04 
Python version | 3.6.5
Pip version | 9.0.1
Manga-py version | 1.3.29.1
URL | https://tmofans.com/library/manga/16660/Hajimete-no-Gal

#### To Reproduce:
1. Step 1 manga-py https://tmofans.com/library/manga/16660/Hajimete-no-Gal

**Comment by 1271** [comment]
Sorry. It is very difficult to solve.
Easier to remove the provider.
Try using a VPN, for example.
From the USA and Italy, it works great.

**Comment by 1271** [comment]
You can get around this by specifying the user-agent of your browser from your browser to manga-py.

For example, I use the Firefox browser:
manga-py --user-agent "Mozilla / 5.0 (X11; Ubuntu; Linux x86_64; rv: 69.0) Gecko / 20100101 Firefox / 69.0"

Anyway. The captcha solution at the level of "select a picture" or "click if not a robot" is not included in the project’s case.
I hope for your understanding.
