### ISSUE TITLE
[question] difference between `--one-thread` and `--no-multi-threads` options

### ISSUE THREAD

**Issue by paulolimac** [manga-py/manga-py#225]
Guys,

what is the difference between `--one-thread` and `--no-multi-threads` options?
And when using each one?

**Comment by 1271** [comment]
Hi @paulolimac.
This is essentially the same thing, but
`--one-thread` will use one thread to load images, while `--no-multi-threads` will be limited to two.
In fact, I think to remove the `--no-multi-threads` option in favor of
`--max-threads <num>`
Then you can specify the maximum number of threads for the utility to work.
By default, the number of threads is equal to the number of processor cores.

**Comment by 1271** [comment]
Please, update manga-py:
```bash
pip install manga-py -U
```

**Comment by paulolimac** [comment]
Understood, @1271.

Asked because their name smells like duplication/ambiguity, like two methods that do the same thing. :smirk: 

Relieved that you perceived that and cleaned the things up, to be done in a more elegant way.

Thanks for your hard work.

**Comment by 1271** [comment]
It was probably done late at night, so I could be sleepy :D

**Comment by paulolimac** [comment]
hahaha, :smile:
