### ISSUE TITLE
Failed to login to exhentai.org

### ISSUE THREAD

**Issue by juh9870** [manga-py/manga-py#229]
# Bug report

Description | Data
---|---
OS | Windows 7
Python version | 3.7.3
Pip version | 19.0.1
Manga-py version | 1.8.5
URL | exhentai,org

Failed to login to exhentai.org

Error log:
[login_error.log](https://github.com/manga-py/manga-py/files/3767192/login_error.log)

URL i tried to download: https://exhentai.org/g/1403504/ff38b6352a/

**Comment by 1271** [comment]
Thank. I'll see today after work

**Comment by 1271** [comment]
Done. Will be in the next release.

**Comment by juh9870** [comment]
Yeah, login works now
