### ISSUE TITLE
Sites down

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#231]
# Request to remove a site

All of this seems to be down

Url to remove | 
---|
http://sosscanlation.com/|
http://readhentaimanga.com/|
http://subapics.com|
https://mangaforall.com/|
http://authrone.com|
https://nude-moon.me/|

**Comment by 1271** [comment]
Thank. I will remove from the list

**Comment by 1271** [comment]
Done. Will be in the next release.

**Comment by gromenauer** [comment]
mangaforall.com still in the list, but this web is in a weird state.

**Comment by 1271** [comment]
If mangaforall is not available for the next update, it will be removed from list
thanks
