### ISSUE TITLE
Request to add 1stkissmanga.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#232]
# Request to add a site

Description | Data
---|---
Url to add | `https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/`

**Comment by 1271** [comment]
Check updates

**Comment by gromenauer** [comment]
Fails for me:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.12.2
URL | `https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/
~~~
~~~
Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!



Current chapter url: https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/chapter-1/

Error processing file: vol_001-0


Current chapter url: https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/chapter-2/

Error processing file: vol_002-0

...

Current chapter url: https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/chapter-42/

Error processing file: vol_042-0


Current chapter url: https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/chapter-43/

Error processing file: vol_043-0
 
~~~

This is how a chapter seems from here:
~~~ bash
wget https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/chapter-1/
~~~ 


[index.html.txt](https://github.com/manga-py/manga-py/files/4051413/index.html.txt)

**Comment by 1271** [comment]
Hm.. i check it. thanks

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.13
URL | `https://1stkissmanga.com/manga/dimensional-mercenary-other-world-warrior/`

Sorry for forgetting to review this one :innocent:
