### ISSUE TITLE
are this application have a GUI display?

### ISSUE THREAD

**Issue by MIRVOUS** [manga-py/manga-py#241]
I want try this application but I'm not familiar with CLI

**Comment by 1271** [comment]
Hi. In fact, everything is much simpler than it seems.
You only need to run manga-py with some parameters
If you are using linux-based system, run bash
If you use windows, run powershell or cmd (win + R)

Example:

```bash
# help:
manga-py -h

# download manga from bato.to (full list of supported sites here: https://manga-py.com/manga-py/):
manga-py https://bato.to/series/73698
```

Simple, right? ^_^

**Comment by MIRVOUS** [comment]
thanks i will try later.

**Comment by 1271** [comment]
If there are difficulties, feel free to ask. They will try to help you
