### ISSUE TITLE
broken: kissmanga and mangahasu.se (maybe it was cloudflare)

### ISSUE THREAD

**Issue by paulolimac** [manga-py/manga-py#245]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Ubuntu 18.04
Python version | 3.6.9
Pip version | 19.2.3
Manga-py version | 1.10.0
URL | http://mangahasu.se/not-a-househusband-p28764.html and https://kissmanga.com/Manga/You-re-the-best-Furby-kun

#### To Reproduce:
1. Download latest mangapy https://github.com/manga-py/manga-py/archive/stable_1.x.zip
2. Unsuccessfully, try mangahasu.su and kissmanga.com:
``` bash
$ python3 ./manga.py http://mangahasu.se/not-a-househusband-p28764.html
...
$ python3 ./manga.py https://kissmanga.com/Manga/You-re-the-best-Furby-kun
```
3. Successfully, try mangadex.org and tapas.io:
```
$ python3 ./manga.py https://mangadex.org/title/43470/bang-dream-the-same-sound-we-make-doujinshi
...
$ python3 ./mp/manga.py https://tapas.io/episode/1256838
```

#### Additional context
The output from terminal got frozen a lot of minutes (no logs, nor error messages).
Maybe cloudflare module is broken here.

**Comment by 1271** [comment]
Please, run:

pip3 install -U -r requirements.txt

**Comment by 1271** [comment]
![изображение](https://user-images.githubusercontent.com/1452243/69912966-5da96100-1442-11ea-8d6f-bdc22f705bb4.png)

If such an error occurs, it means you need to update the packages

**Comment by paulolimac** [comment]
thanks @1271.

For mangahasu, worked well. :smile:

But with kissmanga, it downloaded now, but the files are corrupted (in some way). :disappointed: 
My output:

```
$ python3 ./manga-py/manga.py https://kissmanga.com/Manga/You-re-the-best-Furby-kun
N/A% (0 of 1) |                                                                                          | Elapsed Time: 0:00:02 ETA:  --:--:-- 
100% (1 of 1) |##########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
```

and the *problematic* zip downloaded file:

```
$ unzip -l Manga/You-re-the-best-Furby-kun/001-Oneshot-477490.ERROR.zip 
Archive:  Manga/You-re-the-best-Furby-kun/001-Oneshot-477490.ERROR.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2019-12-02 18:32   000.ƨQu
      124  2019-12-02 18:32   info.txt
---------                     -------
      124                     2 files
```

look that inside the zipfiles, there are not any image files.
i repeated with other kissmanga links, but i got the same problem.

**Comment by 1271** [comment]
Hmmm. I will check it again, thanks

**Comment by 1271** [comment]
Hmmm... I don't have any errors.
I will check from home after work.
![photo_2019-12-03_08-14-36](https://user-images.githubusercontent.com/1452243/70022375-1091d000-15a5-11ea-98c3-2493667c3006.jpg)

Is this url a mistake for you too?
https://kissmanga.com/Manga/Dignified-asleep-SAEKI

**Comment by paulolimac** [comment]
@1271, thanks for your help.
strangely, both sites (kissmanga and mangahasu) worked now. :heavy_check_mark: 
maybe it was a result from some kind of instability.

ps: the [url you asked](https://kissmanga.com/Manga/Dignified-asleep-SAEKI) me opened without problems (by browser and manga-py).
