### ISSUE TITLE
Broken download from manganelo.com

### ISSUE THREAD

**Issue by wilfriedroset** [manga-py/manga-py#250]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Debian 9.11
Python version | 3.5.3
Pip version | 19.3.1
Manga-py version | 1.9.1
URL | https://manganelo.com/manga/kimetsu_no_yaiba

#### To Reproduce:
1. Try to download any manga from https://manganelo.com

#### Additional context
```
manga-py https://manganelo.com/manga/kimetsu_no_yaiba
2019-12-20 11:26:56.752 | WARNING  | manga_py.base_classes.base:_prepare_chapters:130 - Chapters list empty. Check https://manganelo.com/manga/kimetsu_no_yaiba
```

**Comment by gromenauer** [comment]
Edit: Oops this is ok :sweat_smile:, just mangakakalot sometimes reubicates pages to manganelo, and this was it.
~~Same for `mangakakalot.com` (I think it have the same structure)~~

~~Component~~ | ~~Value~~
---|---
~~OS~~ | ~~Ubuntu 16.04.6 LTS~~
~~Python version~~ | ~~Python 3.5.2~~
~~Pip version~~ | ~~pip 19.1.1~~
~~Npm version~~ | ~~3.5.2~~
~~Manga-py version~~ | ~~1.11.0~~
~~URL~~ | ~~`https://mangakakalot.com/manga/ai918670`~~

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages \
  --no-webp   --destination "./Manga/" --name "2_isekai_cheat_survival_meshi"   \
  --show-current-chapter-info   "https://mangakakalot.com/manga/ai918670" 
~~~
~~~
2019-12-22 01:25:05.093 | WARNING  | manga_py.base_classes.base:_prepare_chapters:130 - Chapters list empty. Check https://mangakakalot.com/manga/ai918670
~~~

**Comment by 1271** [comment]
Today will be an update. Thank you for using manga-py

**Comment by 1271** [comment]
i close it
if you have any questions you can create a new issue
thanks
