### ISSUE TITLE
New provider: manga41.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#254]
# Request to add manga41

Description | Data
---|---
Url to add | `https://manga41.com/manga/solo-leveling/`

**Comment by 1271** [comment]
Check updates

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.12.2
URL | `https://manga41.com/manga/solo-leveling/`
