### ISSUE TITLE
Manganelo broken chapter names.

### ISSUE THREAD

**Issue by ghost** [manga-py/manga-py#255]
When i download my manga from manganelo, chapter names were saved as vol0 bla bla.

Description | Data
--- | ---
OS | Arch linux 
Python version | 3.8.1
Pip version | 19.2.3
Manga-py version | 1.12.1
URL | https://manganelo.com/manga/gz921668

**Comment by gromenauer** [comment]
What was the expected output? (Seems OK to me)

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.12.1
URL | `https://manganelo.com/manga/gz921668`


~~~ sh
pipenv run manga-py --cbz --zero-fill --rename-pages \
  --no-webp --show-current-chapter-info \
  --destination /tmp/Manga/ \
  https://manganelo.com/manga/gz921668 \
  --print-json --simulate
~~~
~~~
      "path": "/tmp/Manga/gz921668/vol_001-0.cbz",
      "path": "/tmp/Manga/gz921668/vol_002-0.cbz",
~~~

**Comment by 1271** [comment]
Hey. vol_ * is a normal name for the chapter.
All (or almost all) sites will download chapters with these names
