### ISSUE TITLE
update website

### ISSUE THREAD

**Issue by MarshallTaylorV** [manga-py/manga-py#256]
hello you can update this website thank you

https://www.japscan.co | https://www.japscan.co

**Comment by 1271** [comment]
thanks. Will be in the next update

**Comment by 1271** [comment]
Check updates

**Comment by MarshallTaylorV** [comment]
Hello i tried the last new update but is not working with the url https://www.japscan.co/

**Comment by 1271** [comment]
Oh. My mistake. Please wait a bit

**Comment by MarshallTaylorV** [comment]
Hello Thanks for works but i have some issue look  
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72808886-6c4a1280-3c52-11ea-8525-f521fd11cc50.png)

**Comment by MarshallTaylorV** [comment]
i think issue comes from CloudFlare 
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72809421-78829f80-3c53-11ea-917f-ca3a19a562b9.png)

**Comment by 1271** [comment]
Yeah.
run it:

```
pip install -U cloudscraper
```

**Comment by MarshallTaylorV** [comment]
Yeah i come from to tester but it give that 
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72859326-473dba00-3cbb-11ea-99c4-501f29dad20a.png)

**Comment by MarshallTaylorV** [comment]
and that too
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72859427-b2878c00-3cbb-11ea-9889-23234d7163d2.png)
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72859504-02665300-3cbc-11ea-9831-9437e72584f2.png)

**Comment by 1271** [comment]
Please, use true url:

example:
 `https://www.japscan.co/manga/nanatsu-no-taizai/`
 `https://www.japscan.co/manga/kimetsu-no-yaiba/`

https://www.japscan.co/mangas/

**Comment by MarshallTaylorV** [comment]
Thank you so kind and patient 🎉

**Comment by MarshallTaylorV** [comment]
I already have the volume Kimetsu no Yaiba Tome from 1 to 18 like this 
![Sans titre 3](https://user-images.githubusercontent.com/28553653/72903100-88b67f80-3d24-11ea-80e4-44bec1b85c2c.png)

**Comment by MarshallTaylorV** [comment]
is it possible to download volume 19 directly without redownloading all volumes from 1 to 22?

**Comment by MarshallTaylorV** [comment]
or to download directly from 19 to 20 in cbz what are the command lines to do its?

**Comment by 1271** [comment]
`manga-py -h` - help
`manga-py -s N`  - skip N chapters
`manga-py -c N` - download only N chapters

example:
`manga-py -s 2 -c 3 http://manga/here` - download only chapters 3 to 5

**Comment by MarshallTaylorV** [comment]
Thank you very much my friend  😄🙏🏼
