### ISSUE TITLE
Add "alias": mangadex.cc (= mangadex.org)

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#257]
# Request to add a site

Mangadex is down, while fixing it they are serving through mangadex.cc

Description | Data
---|---
Url to add | `https://mangadex.cc`

Example: `https://mangadex.cc/title/39036/that-inferior-knight-lv-999`

**Comment by 1271** [comment]
thanks. Will be in the next update

**Comment by 1271** [comment]
Check updates

**Comment by gromenauer** [comment]
Works OK :+1: in `manga-py` version `1.12.2`

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.12.2
URL | `https://mangadex.cc/title/39036/that-inferior-knight-lv-999`

**Comment by gromenauer** [comment]
Strange filenames came out:

~~~
-ch_4.1.cbz
-ch_4.2.cbz
-ch_4.4.cbz
-ch_4.3.cbz
~~~

Sould it be?:
~~~
vol_004-1.cbz
vol_004-2.cbz
vol_004-3.cbz
vol_004-4.cbz
~~~

Try with:
~~~ bash
echo gb | pipenv run manga-py \
  --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
  --destination Manga/ https://mangadex.cc/title/39036/that-inferior-knight-lv-999 \
  --simulate --print-json | grep path
~~~
~~~
Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_2.3.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.5.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.9.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.1.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_2.2.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.6.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.3.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/-ch_4.1.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.4.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.1.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.3.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.2.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/-ch_4.2.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_2.1.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.2.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/-ch_4.4.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_2.4.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/-ch_4.3.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_1.4.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.8.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.7.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.5.cbz",
      "path": "Manga/That Inferior Knight, Lv. 999/vol_001-ch_3.6.cbz",
~~~

**Comment by gromenauer** [comment]
Another example:

`https://mangadex.cc/title/36646/the-swordsman-called-the-countless-swords-sorcerer`

Time | Filenames
--- | ---
Previous filename | vol_001-ch_1-English.cbz
New filename | vol_001-ch_1.cbz

**Comment by 1271** [comment]
Oh. i check it. thanks

**Comment by 1271** [comment]
Not sure if I can fill out a “chapter” for this particular manga.
The chapter is simply not indicated for some references.
![изображение](https://user-images.githubusercontent.com/1452243/72304973-58674500-3683-11ea-9e46-5797a22a342f.png)


I'm afraid I cannot fill out a "chapter" for this particular manga.
The chapter was simply not indicated for some links.
![изображение](https://user-images.githubusercontent.com/1452243/72277079-55983000-3642-11ea-8c68-f5bae8e0db36.png)

**Comment by gromenauer** [comment]
It seemed to me that volume was defaulted to `0` when no `Vol. \d+` is present.
___
`mangadex.org` is back
`mangadex.info` and `mangadex.com` seems that are no longer comics.

**Comment by 1271** [comment]
As I see, the domains were sold
Sites may work on different urls, but I'm not sure.

> `mangadex.org` is back

Ok. I will recheck provider

**Comment by gromenauer** [comment]
> Sites may work on different urls, but I'm not sure.

Have you thought in site "fingerprinting"? Maybe something as: 
* Main page have this xpath_1, chapters are in this xpath2. New sites with xpath1 and xpath2 could work with this provider. (Too simplistic?)

**Comment by 1271** [comment]
This does not always work and requires reworking the provider system.
Theoretically, this can be implemented even now, but I'm not sure

**Comment by gromenauer** [comment]
Think of the "fingerprinting" as an assert. An extra check that the provider can have (or not) and tells you immediately that the site changed and now is broken. Advantages:
* More specific errors: "URL xxx. Page reader assert #１ failed".
* Easily know that one new url could correspond to an existing provider.

**Comment by gromenauer** [comment]
It's working :+1:
