### ISSUE TITLE
random download

### ISSUE THREAD

**Issue by Vladimir-A** [manga-py/manga-py#261]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | linux kernel 5.5.2
Python version | 3.8.1
Pip version | 19.3
Manga-py version | 1.13
URL | https://*.cafe/

#### To Reproduce:
1. manga-py https://*.cafe/
2. | WARNING  | manga_py.base_classes.base:_prepare_chapters:130 - Chapters list empty. Check https://*.cafe/

#### Additional context
Some titles download others no. https://*.cafe/ website from https://manga-py.com/manga-py/ list.

**Comment by 1271** [comment]
Please provide an example of a broken link. Thanks

**Comment by binazawa-0740** [comment]
@1271, Manga-py version - 1.16.2, Python 3.8.2, pip 20.0.2
Works with:
https://hentai.cafe/manga/read/ryu-shinonome-make-me-happy/en/0/1/page/1
Doesn't works with:
https://hentai.cafe/manga/read/just-a-repetition-of-love/en/0/1/page/1
Error:
| WARNING  | manga_py.base_classes.base:_prepare_chapters:133 - Chapters list empty. Check https://hentai.cafe/manga/read/just-a-repetition-of-love/en/0/1/page/1

**Comment by 1271** [comment]
Thanks for the help. I will check it
