### ISSUE TITLE
Manganelo url fix

### ISSUE THREAD

**Issue by ghost** [manga-py/manga-py#263]
Manganelo changed their url as m.manganelo.com when you clicked on spesific manga.

**Comment by 1271** [comment]
For me, the site is working fine.
Does this cause problems?

Provider must work with any address (it seems)

**Comment by ghost** [comment]
Hi, i found out it. Manganelo has two type url. First one is simple manganelo.com second one is m.manganelo.com. First one works quite good. Thanks your reaching out!

**Comment by 1271** [comment]
Not problem 👍
