### ISSUE TITLE
Convert To Pdf

### ISSUE THREAD

**Issue by shahzaib78631** [manga-py/manga-py#264]
Can you please add the option for converting the downloaded manga to pdf format.

**Comment by 1271** [comment]
Wait a bit. I will send this to pypi
See https://github.com/manga-py/img2pdf

**Comment by 1271** [comment]
Done. See https://github.com/manga-py/img2pdf

Example:

```bash
# download manga
manga-py http://site/with/manga -d Manga/my_manga
# convert to pdf
manga_py.img2pdf Manga/my_manga -o output_directory
```

**Comment by 1271** [comment]
i close it issue
