### ISSUE TITLE
Add support for bulk download.

### ISSUE THREAD

**Issue by hashc4t** [manga-py/manga-py#265]
# Request to add support for bulk download
A command line flag that would take links from a file would be amazing.
An example would be: 
`manga-py -i text_file_containing_links`
 to download all the links specified in the text file.

**Comment by gromenauer** [comment]
Not what you asked, maybe more convoluted, https://github.com/gromenauer/manga_py_update

**Comment by 1271** [comment]
Or this:

```bash
for i in $(cat text_file_containing_links); do manga-py "$i"; done
```

**Comment by hashc4t** [comment]
Thank you. I will try this. But an included flag would still be nice.

**Comment by 1271** [comment]
This feature will be discussed in manga-py 2
Thanks
