### ISSUE TITLE
☠ Down: boredomsociety.xyz nozominofansub.com ...

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#266]
# Request to remove sites

* [x] `https://www.boredomsociety.xyz/`
* [x] `http://nozominofansub.com/`
* [ ] `https://remanga.org/`
* [x] `http://mangaforall.com/`
* [x] `http://manga-room.com/`
* [x] `http://manga.animefrontline.com/` 
* [x] `http://manhwa.co/` 
* [x] `http://exhentai.org/` 
* [x] `http://npscan.mangaea.net/` 
* [x] `http://snf.mangaea.net/` 
* [x] `http://zip-read.com/` 
* [x] `http://freemanga.to/`

**Comment by 1271** [comment]
Thx

**Comment by 1271** [comment]
remanga.org works for me, i will not delete now

**Comment by gromenauer** [comment]
Tnkx!
