### ISSUE TITLE
😱 mangakakalot.com: Url format changed

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#272]
# Bug report

Provider mangakakalot.com changed it's url format.

Format | Example
--- | ---
Old format |`https://mangakakalot.com/manga/tsuki_ga_michibiku_isekai_douchuu` 
New format |`https://mangakakalot.com/read-kg6sn158504832577`

Environment :

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.14
URL | `https://mangakakalot.com/read-kg6sn158504832577`

#### To Reproduce:
~~~ bash
pipenv run manga-py \
  --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  https://mangakakalot.com/read-kg6sn158504832577
~~~

#### Additional context
Output
~~~
    raise AttributeError('Provider not found')
~~~

**Comment by gromenauer** [comment]
Some url remain the same. Example:
~~~
https://mangakakalot.com/manga/rm922554
~~~

I'm suspecting that `https://mangakakalot.com/read-.*` is some kind of gateway to manganelo.com

Example:

Manga "It's Sudden, but I came to Another World! But I hope to live Safely"

Type|URL
---|---
Manga | https://mangakakalot.com/read-iw9rf158504883256
Manga | https://manganelo.com/manga/lk918931
Chapter | https://mangakakalot.com/chapter/lk918931/chapter_1
Chapter | https://manganelo.com/chapter/lk918931/chapter_1

read-iw9rf158504883256 → lk918931

I could workaround it manually searching every equivalent in manganelo... but I have hundreds, and is too much.

**Comment by 1271** [comment]
Ok  (^_^)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.14.2
URL | `https://mangakakalot.com/read-kg6sn158504832577`

**Comment by gromenauer** [comment]
OOps! Not everything is working. Old style url are failing.
Sorry.

Component | Value
---|---
OS | Docker: Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.14.2
URL | :+1:  `https://mangakakalot.com/read-kg6sn158504832577`
URL | :bug: `https://mangakakalot.com/manga/zero_no_shiniki`
URL | :bug: `https://mangakakalot.com/manga/rm922554`

~~~ py
manga-py https://mangakakalot.com/manga/zero_no_shiniki 

Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

  File "/usr/local/lib/python3.6/site-packages/manga_py/__init__.py", line 44, in _init_cli
    cli_mode.start()
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 44, in start
    'Make sure that your inputed URL is correct\n\nTrace:',
~~~

~~~ py
manga-py https://mangakakalot.com/manga/rm922554

Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

  File "/usr/local/lib/python3.6/site-packages/manga_py/__init__.py", line 44, in _init_cli
    cli_mode.start()
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 44, in start
    'Make sure that your inputed URL is correct\n\nTrace:',
~~~

**Comment by 1271** [comment]
Yes it is. I removed support for old links.

P.S. returned. Will be in the next release


P.P.S.
Oh...
I misunderstood you. They now have 2 address formats... Fixed

**Comment by 1271** [comment]
Waiting travis (https://github.com/manga-py/manga-py/issues/275#issuecomment-612406429)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.18.1
URL | `https://mangakakalot.com/read-kg6sn158504832577`
URL | `https://mangakakalot.com/manga/zero_no_shiniki`
URL | `https://mangakakalot.com/manga/rm922554`
