### ISSUE TITLE
Feature: Redirection management

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#275]
# Feature request
**Is your feature request related to a problem? Please describe.**
Yes. Redirections aren't warned in `manga-py`, and I think that it is a good thing to have.

Following the redirection is good temporary remedy (don't know if manga-py does it), but redirections (in my opinion) should be warned. This enables the user to change the invocation method.

A URL redirected could be deleted from the web server after a time. Keeping up to date the sources of the manga is needed when a manga is long lived.

Use case:
* User downloads manga from `URL_1`
* User downloads manga from `URL_1`
* Time pass
* Web server changes manga location to `URL_1b` and redirects `URL_1` → `URL_1b`
* If `manga-py` follows redirections (don't know if `manga-py` does it):
  * User ask for manga from `URL_1`, `manga-py` downloads manga from `URL_1b`
  * Time pass
  * Web server changes deletes redirection `URL_1` → `URL_1b`
  * User ask for manga from `URL_1` and gets an error
* If `manga-py` don't follows redirections:
  * User ask for manga from `URL_1` and gets an error

**Describe the solution you'd like**
* Detect redirections when possible
* Print a warning when a redirection is discovered. Example:
~~~
WARNING: Redirection (old=https://mangakakalot.com/manga/uo918468 new=https://mangakakalot.com/read-nb7ii158504887795) Please remember the redirection for future invocations.
~~~

**Additional context**
Very usual in mangakakalot. Example:

`https://mangakakalot.com/manga/uo918468` is now redirected to `https://mangakakalot.com/read-nb7ii158504887795`

**Comment by 1271** [comment]
> Very usual in mangakakalot

manga-py cannot see this redirect, because is javascript redirect

![изображение](https://user-images.githubusercontent.com/1452243/78809748-0b6be400-79d0-11ea-8f5e-e6e63b5dc5ab.png)


Regard regular redirects - this can be done, but I'm not sure about all sites

**Comment by 1271** [comment]
i have idea!
Check [hoper](https://github.com/1271/hoper) ^_^

This utility was specially for check redirects

```bash
pip install hoper

hoper http://google.com
# or
python -m hoper http://google.com
```

**Comment by gromenauer** [comment]
Tried it with no luck. Javascript redirects are certainly tricky.

~~~ bash
docker run -i --rm mangadl/manga-py

PATH=/home/manga/.local/bin:$PATH
pip3 install --user --upgrade pip hoper
python3 -m hoper https://mangakakalot.com/manga/uo918468

Hope:	https://mangakakalot.com/manga/uo918468
Status:	200
~~~

**Comment by 1271** [comment]
Check help ^_^
The problem is that js forces the entire page to download. It's really slow, but it's worked )

```
hoper https://mangakakalot.com/manga/uo918468 -j
```

![изображение](https://user-images.githubusercontent.com/1452243/79043088-9a157680-7c05-11ea-8436-c156dcad5fcd.png)

**Comment by 1271** [comment]
For version 1.1:
```
hoper http://mangakakalot.com/manga/uo918468 -lj > last_url.txt
```

P.S. travis  "Under Maintenance" now (https://www.traviscistatus.com/)
Waiting...


P.P.S. **Released**

**Comment by 1271** [comment]
Waiting travis (https://github.com/manga-py/manga-py/issues/275#issuecomment-612406429)

**Comment by gromenauer** [comment]
hoper + docker works OK :+1:
