### ISSUE TITLE
Docker has old openssl (1.0.1t)

### ISSUE THREAD

**Issue by xxlbug** [manga-py/manga-py#276]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Docker on linux
Python version | 3.6.8
Manga-py version | 1.14.1
URL | http://www.mangahere.cc/manga/the_last_human/

#### To Reproduce:
1. install docker from https://hub.docker.com/r/mangadl/manga-py
2. try to download e.g. http://www.mangahere.cc/manga/the_last_human/
3. get `DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.1t  3 May 2016) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.`
4. for this url you get the following error `[AttributeError("'NoneType' object has no attribute 'group'",)]`
5. for this url same error but download is ok: http://fanfox.net/manga/solo_leveling/

**Comment by 1271** [comment]
It's official debian ssl version. See here: https://packages.debian.org/jessie/openssl

> 1.14.1

Please, try 1.14.2
It's worked for me

**Comment by 1271** [comment]
P.S. its realy works. For latest version ( :latest)
![image](https://user-images.githubusercontent.com/1452243/79017733-be784100-7b7a-11ea-8e97-41b424baf067.png)

**Comment by xxlbug** [comment]
![image](https://user-images.githubusercontent.com/1849886/79017900-be744300-7b72-11ea-8b78-7218ed472e32.png)

tried the latest docker first, same error with the 1.14.2 -> try this url http://www.mangahere.cc/manga/the_last_human

**Comment by 1271** [comment]
Yeah.. I see it
Hmmm...
I will think about what can be done with this.
Now you can at least install manga-py as a package in your virtual environment until the problem is fixed

Thanks

**Comment by 1271** [comment]
New docker image building now

**Comment by xxlbug** [comment]
wow, nice response time :-)
thank you

**Comment by 1271** [comment]
I just replaced one line. It was not difficult.
Thanks for the report.

P.S. docker.com is delaying the build again. The new container should be within 25-30 minutes

**Comment by xxlbug** [comment]
Ok, ssl error went away, the downloading error is still there 
![image](https://user-images.githubusercontent.com/1849886/79022070-727acb80-7b7d-11ea-8687-7ae538d88a53.png)

**Comment by 1271** [comment]
Waiting travis (https://github.com/manga-py/manga-py/issues/275#issuecomment-612406429)

**Comment by 1271** [comment]
Check updates

**Comment by 1271** [comment]
It works? Can I close this issue?

**Comment by xxlbug** [comment]
Thank you, working fine for me now!
