### ISSUE TITLE
no mangakuki website working

### ISSUE THREAD

**Issue by chinu999** [manga-py/manga-py#280]
(base) C:\Users\DEV>manga-py --skip-volumes 2 --max-volumes 1 https://mangazuki.online/mangas/arafoo-kenja-no-isekai-seikatsu-nikki/
Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

2020-04-17 18:54:50.582 | ERROR    | manga_py.cli:start:44 - Please check if your inputed domain is supported by manga-py:
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:

**Comment by gromenauer** [comment]
@chinu999, Could you try again with the new version.

I tried, it waited at the beginning, and had to retry to download some chapter (maybe fault on the web?), but works OK  for me :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.1
URL | `https://mangazuki.online/mangas/arafoo-kenja-no-isekai-seikatsu-nikki/`

**Comment by 1271** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
Thanks for using manga-py
