### ISSUE TITLE
Add a way to specify the language in the command

### ISSUE THREAD

**Issue by floriplum** [manga-py/manga-py#281]
# Feature request
**Is your feature request related to a problem? Please describe.**
It looks like the currently is no way to specifiy the language for sites like mangadex in the command.

**Describe the solution you'd like**
I think a feature to specify the language as a flag would be nice.
So something like --language "$language" to download the specific language.

**Describe alternatives you've considered**
Piping the desired language to manga-py is already working, so if it would be to difficult to implement.
So something like "echo 'gb' | manga-py '$URL' is already working.

**Comment by 1271** [comment]
Yes you are right. But there are only a couple of such sites, so at the moment adding a language option is not considered.
I’ll think about what you can think of without adding any extra arguments.
Maybe it will be something like
`--arguments language=gb password=my-password login=my-login`

Thanks for issue

**Comment by floriplum** [comment]
As mentioned, the option with piping the wanted language already is working fine.
So take your time :)

**Comment by 1271** [comment]
Ok. I close it. If you have one more problem/question, create new issue.

Thanks for use manga-py.
