### ISSUE TITLE
Handle volumes with multiple groups available.

### ISSUE THREAD

**Issue by floriplum** [manga-py/manga-py#282]
# Feature request
**Is your feature request related to a problem? Please describe.**
When downloading a entire series from Mangadex, it looks like there is no real way to specify from what group the content will be downloaded.

**Describe the solution you'd like**
If i download manga-x and both group-a and group-b translated it and option to select which group you like would be cool.

I think one of the following methods would be cool:

- Specify what group you want. For example --group "group-a"
- Specify to download the volume from the group with more views. Depending on how you parse the data this might be difficult since i cant find the view number in the API.
- An option to Download both releases, and add the group name to the file so you could decide late.

**Describe alternatives you've considered**
If this all would be to hard to add it would be cool if you could at least tell me how same volumes from different groups are currently handled.

**Comment by 1271** [comment]
Yes you are right. But there are only a couple of such sites, so at the moment adding a language option is not considered.
I’ll think about what you can think of without adding any extra arguments.
Maybe it will be something like
`--arguments language=gb password=my-password login=my-login`

Thanks for issue

**Comment by 1271** [comment]
see https://github.com/manga-py/manga-py/issues/281#issuecomment-616080435

Maybe `--arguments translator=awesome-translator`

I will try to do it, but I can’t promise you that.

**Comment by floriplum** [comment]
Do you know how it is currently handled when you have the same volume twice?

**Comment by 1271** [comment]
If I understand you correctly:

Now doubles will just be skipped

**Comment by 1271** [comment]
You can try new version:

`pip install manga-py==1.18b0`

This is a beta version and there can be many bugs :D

**Comment by floriplum** [comment]
This looks like it is working as expected.

If not to complicated an option would be cool to download multiple/all groups and put that group name in the filename. If you have a manga with a few hundred releases and groups that change every few releases it would be time consuming to search for every group and specify all of them.

Still great job on the arguments option.

**Comment by 1271** [comment]
You do not need to filter everything. This is optional.
Sorry, I do not want to turn this into graphql

**Comment by floriplum** [comment]
I meant an option that basically adds the group name to the file name, but its fine if it is not something you want to do.

**Comment by 1271** [comment]
Oh. Yes, I can add a group name.

**Comment by 1271** [comment]
Also yesterday I thought about adding a few groups, but still I don't think it's a good idea.
One and the same group can translate well one manga and badly another.
In any case, you have to keep track of what you need to download.

**Comment by floriplum** [comment]
That is true, the reason i thought it would be helpful were the mangas with often changing groups. Sometimes when the group changes they overlap a bit, so group a uploads 1-55 and group b uploads 50 -70. Now it would be cool if i could get the number 50-55 from both groups and just have the file a bit renamed.

This way i know what i get but dont need to start a fresh download with each group specified, and could just locally compare what group i want to read.

**Comment by 1271** [comment]
OK. Sounds good.
Will be in the next release.

**Comment by floriplum** [comment]
Nice this would make my text wrapper for manga-py a little cleaner :)

**Comment by floriplum** [comment]
Btw would someting like a text file input option make sense for manga-py?

**Comment by 1271** [comment]
I do not understand.

**Comment by 1271** [comment]
Can you give an example?

**Comment by floriplum** [comment]
Since i like to automate my stuff i have services like youtube-dl and others to update one time a day from a list.

So basically an flag like --input-file to use a file as input for urls.

I know this is probably stuff for another issue but i wanted to ask before i open a new issue.

**Comment by 1271** [comment]
It's impossible now. And perhaps it will be impossible in the future.
If you need to download multiple manga, you can do it now.
`for i in $(cat /manga/list); do manga-py $i; done`

If you need to store some more settings, you can make a simple wrapper for manga-py
Believe me, it’s not difficult

**Comment by floriplum** [comment]
Yeah i already made a wrapper, i was just wondering if there is a plan to implement something like this.

**Comment by 1271** [comment]
manga-py was not intended as a universal tool. Initially it was generally just a script from 1 python file.
Therefore... Idk 😁

**Comment by gromenauer** [comment]
My manga-py 1.x wrapper https://github.com/gromenauer/manga_py_update works for me. :innocent:

**Comment by 1271** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
