### ISSUE TITLE
i can't install or update manga-py

### ISSUE THREAD

**Issue by chinu999** [manga-py/manga-py#283]
(base) C:\Users\DEV>pip install manga-py
Collecting manga-py
  Using cached manga_py-1.17.tar.gz (106 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\DEV\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DEV\\AppData\\Local\\Temp\\pip-install-g77txsy2\\manga-py\\setup.py'"'"'; __file__='"'"'C:\\Users\\DEV\\AppData\\Local\\Temp\\pip-install-g77txsy2\\manga-py\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\DEV\AppData\Local\Temp\pip-install-g77txsy2\manga-py\pip-egg-info'
         cwd: C:\Users\DEV\AppData\Local\Temp\pip-install-g77txsy2\manga-py\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DEV\AppData\Local\Temp\pip-install-g77txsy2\manga-py\setup.py", line 26, in <module>
        with open('requirements.txt', 'r') as r:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

and can you tell me how to install old version
or
downgrade

**Comment by 1271** [comment]
Oh. You're right. Please try in 15 minutes

**Comment by 1271** [comment]
Sorry for this bug

**Comment by chinu999** [comment]
thanks bro every thing works fine expect some specfic manhwa and manga.

**Comment by 1271** [comment]
Can you give an example?

**Comment by 1271** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
