### ISSUE TITLE
Check if the downloaded content is actually an image

### ISSUE THREAD

**Issue by floriplum** [manga-py/manga-py#284]
# Feature request
**Is your feature request related to a problem? Please describe.**
I noticed that when i use your tool on a site like manganelo, and for some reason the server serving the images is not working(so ofc the image is also not visible in any browser). Then manga-py is still trying to download the file, that now only contains "This content is temporarily unavailable- Please try again later"

**Describe the solution you'd like**
Maybe add some sort of check if the file really contains data or check for the file size.
In the end some kind of error message would be nice, since it showed no problem when i tried to download the content, but all i got was textfiles containing the error message(all named like the actual image file).

**Describe alternatives you've considered**
Not sure how easy something like the bsd-file(or the corelibs one) command would be, since it tells me correctly that the downloaded file is "ASCII text, with no line terminators".

**Comment by 1271** [comment]
Can you give an example?
Link to the manga.

**Comment by floriplum** [comment]
Sorry i forgot about to post it.
In this case it was this chapter "https://manganelo.com/chapter/tvhs235861561861720/chapter_152"
The previous Chapter is working if you need a reference.

**Comment by 1271** [comment]
Check it
`pip install manga-py==1.18b1`

**Comment by floriplum** [comment]
After changing to this Version it looks like it wont download anything at all.

**Comment by 1271** [comment]
Oh... Fixed ^_^

**Comment by floriplum** [comment]
Thanks for the quick fix XD
It looks like it is correctly detecting that something is wrong with the Version `1.18b1`.

If it detects missing images, do you intend to abort this chapter then?

**Comment by 1271** [comment]
No, at the moment these images will be skipped and an error message will be displayed.

**Comment by 1271** [comment]
The name of the archive will also indicate "ERROR" (see `1.18b3` version)

**Comment by floriplum** [comment]
This would obviously be even better, but it currently looks like it is not working with the new beta.

**Comment by 1271** [comment]
Are you sure?
If one of the images is skipped, the archive should have "ERROR" in its name

**Comment by 1271** [comment]
Please, check `manga-py --version` its `beta.3`

**Comment by 1271** [comment]
Hmmm... Yes you are right. I will check it

**Comment by floriplum** [comment]
When i get an chapter with an error i get the following error message `[NotImplementedError()]`. I double check and i have indeed the version beta.3

**Comment by 1271** [comment]
Yeah, I tried to run it on another PC and really see this error

**Comment by 1271** [comment]
A complete error is always available with the `--debug` option

**Comment by floriplum** [comment]
I cant seem to reproduce the error i got, anyway [here](https://gist.github.com/floriplum/5bbdcc8b9f53a093e1263c45ff6dab39) is the debug output if still needed.

**Comment by 1271** [comment]
Please, check beta4
This should work correctly.

**Comment by floriplum** [comment]
Now it is adding "IMAGES_SKIP_ERROR" to the archive, but after a while it stops with the following error.
`File "/home/florian/.local/lib/python3.7/site-packages/manga_py/provider.py", line 103, in process`
`self.loop_chapters()`
`File "/home/florian/.local/lib/python3.7/site-packages/manga_py/provider.py", line 140, in loop_chapters`
`self._download_chapter()`
`File "/home/florian/.local/lib/python3.7/site-packages/manga_py/provider.py", line 121, in _download_chapter`
`raise e`
`File "/home/florian/.local/lib/python3.7/site-packages/manga_py/provider.py", line 116, in _download_chapter`
`self._storage['files'] = self.get_files()`
`File "/home/florian/.local/lib/python3.7/site-packages/manga_py/providers/manganelo_com.py", line 26, in get_files`
`raise RuntimeError('Images not found')  # TODO: Just don't know what to do here
`

**Comment by 1271** [comment]
Unfortunately, this is a mistake due to the unstable operation of the site. I can not influence it

Sometimes the site manganelo gives an empty list of images.

**Comment by floriplum** [comment]
I just tried it on another machine(with a different public IP), like you said it looks like a problem with the website. Maybe they limited me since i tested to much :)

Note: it still kinda looks like that the non beta `1.16` version get's more chapters without errors compared to the beta Version. But that could also only be bad luck.

**Comment by 1271** [comment]
In the beta version, only the fact that there is correctly displayed an error about the absence of images

**Comment by floriplum** [comment]
Yeah i noticed that the the update somehow broke the download.

I tried it out a few times and this were the results.
test nr.|16.3|beta4(files without Image error in name)|beta4(files with image error in name)|
| ------|------|-----|-----|
|1|166|11|27|
|2|153|11|25|
|3|164|11|25|
|4|166|11|27|
|5|165|11|27|

**Comment by 1271** [comment]
1.16 does not add error message
You can check this by unpacking the archives or by comparing the sizes.

**Comment by 1271** [comment]
P.S. you should not specify --debug by default. This causes manga-py to abort on error.

**Comment by floriplum** [comment]
I already deleted the files with unreasonable small file sizes, and looked through the files by unzipping them and checking if it is an image or not.
And i thought it was kinda strange that i always got only 11 good chapters every time with the beta. 
Note: i didnt include --debug for this test.

**Comment by 1271** [comment]
![изображение](https://user-images.githubusercontent.com/1452243/79754875-dbea9f00-8320-11ea-80aa-d9f78f7017c7.png)
Chapter 152 now

**Comment by 1271** [comment]
![изображение](https://user-images.githubusercontent.com/1452243/79756158-dee68f00-8322-11ea-94b1-b44093847657.png)
Thanks! I found a reason! You are right

I will fix it today

**Comment by 1271** [comment]
@floriplum check update, please.

`pip install manga-py==1.18b5 -U --no-cache`

**Comment by gromenauer** [comment]
Manganelo (and mangakakalot) have two image sources ("images server 1 & 2" in the snapshot of two comments ago).
Is too complex to get the image from the secondary server when it fails? Maybe it makes sense as a solution.

**Comment by 1271** [comment]
manga-py will get 2 copies of pages for each chapter. But it is real.
Although both image servers seem to be broken at the same time

**Comment by 1271** [comment]
It seems that something really broke on manganelo

![изображение](https://user-images.githubusercontent.com/1452243/79832130-6da1ed00-83b1-11ea-8aea-3be2c40da3be.png)

**Comment by 1271** [comment]
Done. Now manga-py has check first image and if it's broken, try changing cdn

**Comment by floriplum** [comment]
I only tested it a bit, but so far it looks good.

Thank you very much.

**Comment by 1271** [comment]
Thank you for using manga-py

If @gromenauer no complaints, I think I'll release soon

**Comment by gromenauer** [comment]
Works for me :+1: 

Tried in docker (I'm strangely stuck in manga-py version 1.16.2 outside docker).

 <details>
  <summary>Console output:</summary>

~~~ bash
docker run \
>   --interactive \
>   --tty \
>   --rm \
>   --name "manga-py" \
>   -v $PWD:/home/manga/Manga \
>   mangadl/manga-py /bin/bash
manga@91bf27ae37b2:~$ {
> PATH=/home/manga/.local/bin:$PATH
> python3 -m pip install --user --upgrade pip
> python3 -m pip install --user manga-py==1.18b6
> }
...
Successfully installed manga-py-1.18b6
manga@91bf27ae37b2:~$ manga-py \
>   --cbz \
>   --zero-fill \
>   --rename-pages \
>   --no-webp \
>   --show-current-chapter-info \
>   -s 150 \
>   https://manganelo.com/manga/tvhs235861561861720

100% (20 of 20) |##############################| Elapsed Time: 0:00:07 Time:  0:00:07
100% (22 of 22) |##############################| Elapsed Time: 0:00:07 Time:  0:00:07
100% (20 of 20) |##############################| Elapsed Time: 0:00:17 Time:  0:00:17
100% (18 of 18) |##############################| Elapsed Time: 0:00:04 Time:  0:00:04
100% (19 of 19) |##############################| Elapsed Time: 0:00:05 Time:  0:00:05
100% (20 of 20) |##############################| Elapsed Time: 0:00:05 Time:  0:00:05
100% (19 of 19) |##############################| Elapsed Time: 0:00:13 Time:  0:00:13
100% (19 of 19) |##############################| Elapsed Time: 0:00:13 Time:  0:00:13
100% (21 of 21) |##############################| Elapsed Time: 0:00:08 Time:  0:00:08
100% (19 of 19) |##############################| Elapsed Time: 0:00:08 Time:  0:00:08
100% (19 of 19) |##############################| Elapsed Time: 0:00:14 Time:  0:00:14
100% (18 of 18) |##############################| Elapsed Time: 0:00:08 Time:  0:00:08
100% (21 of 21) |##############################| Elapsed Time: 0:00:08 Time:  0:00:08
100% (19 of 19) |##############################| Elapsed Time: 0:00:09 Time:  0:00:09
100% (19 of 19) |##############################| Elapsed Time: 0:00:07 Time:  0:00:07
100% (19 of 19) |##############################| Elapsed Time: 0:00:08 Time:  0:00:08
100% (21 of 21) |##############################| Elapsed Time: 0:00:09 Time:  0:00:09
100% (21 of 21) |##############################| Elapsed Time: 0:00:07 Time:  0:00:07
 
100% (19 of 19) |##############################| Elapsed Time: 0:01:57 Time:  0:01:57
manga@91bf27ae37b2:~$   
~~~
</details>

**Comment by 1271** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
