### ISSUE TITLE
Flag to hide reminders

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#285]
# Feature request
**Is your feature request related to a problem? Please describe.**
When using [manga_py_update](https://github.com/gromenauer/manga_py_update) I got a remainder to visit all sites from my browser from every download. It makes more difficult to read the output and spot problems in the downloads.

**Describe the solution you'd like**
A flag to disable the web reminder.
~~~ py
    print('\n'.join((
        'Please remember that all sites earn on advertising.',
        'Remember to visit them from your browser.',
        'Thanks!\n'
    )), file=stderr)
~~~
Maybe `--i-will-remember-to-visit-the-site` , `--hide-reminders` or `--🙈`

**Comment by 1271** [comment]
Oh. I knew that one day someone would get tired of it :-)

I will show this notification only 1 time during installation

**Comment by gromenauer** [comment]
Works for me :+1: 
Tried in docker, see https://github.com/manga-py/manga-py/issues/284#issuecomment-617773476

**Comment by 1271** [comment]
Thank you for your help!  :smile:
