### ISSUE TITLE
🐛 Bug: --show-current-chapter-info not working

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#291]
# Bug report

Environment 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.18.2

#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py mangadl/manga-py /bin/bash
manga-py --show-current-chapter-info \
  https://mangakakalot.com/read-ed1la158504833308 -c 2
100% (9 of 9) |##################################| Elapsed Time: 0:00:03 Time:  0:00:03
100% (10 of 10) |################################| Elapsed Time: 0:00:01 Time:  0:00:01
 ~~~

#### Additional context

Tried previous versions:

Version | show-current-chapter-info
---|---
1.7.0 | ✔
1.8.0 | ✔
1.15  | ✔
1.16.1 | ✔
1.16.3 | ✔
1.17 | ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
1.17.1 | ✘
1.18.2 | ✘

Tried it using:

~~~ bash
docker run --interactive --tty --rm --name manga-py debian:buster-slim /bin/bash

apt install python3 python3-pip
python3 -m pip install --user --upgrade pip
PATH=/root/.local/bin:$PATH

VERSION=1.17
python3 -m pip install --user --upgrade "manga-py==$VERSION"
manga-py --show-current-chapter-info -c 2 \
  https://lhtranslation.net/manga-jui-san-no-oshigoto-in-isekai.html
~~~

**Comment by 1271** [comment]
Oh. This is not a bug, but I change it.

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.1

I see, seems that it worked when `--debug`, thanks for changing it anyway.
