### ISSUE TITLE
🤦 Windows paths in docker

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#294]
# Bug report

Messages with windows paths appears in some warnings/errors while calling manga-py from docker.
It's strange. Don't remove any functionality for this, only take a look to prevent that this is anything to be concerned.

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.3
URL | `https://merakiscans.com/manga/my-wife-is-a-demon-queen/`
   
~~~ bash       
docker run --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info --quiet \
    https://merakiscans.com/manga/my-wife-is-a-demon-queen/
~~~

~~~
"W:/manga_py/base_classes/base.py:102:2020-05-05 19:11:33,264:Chapters list empty. Check https://merakiscans.com/manga/my-wife-is-a-demon-queen/"
~~~

Same command for `http://www.funmanga.com/isekai-maou-to-shoukan-shoujo-dorei-majutsu`
Output:

~~~
Current chapter url: https://www.funmanga.com/isekai-maou-to-shoukan-shoujo-dorei-majutsu/ 50.2/all-pages

"E:/manga_py/provider.py:149:2020-05-05 19:11:51,077:Error processing file: vol_ 50-2"


Current chapter url: https://www.funmanga.com/isekai-maou-to-shoukan-shoujo-dorei-majutsu/ 47.2/all-pages

"E:/manga_py/provider.py:149:2020-05-05 19:11:52,323:Error processing file: vol_ 47-2"
~~~

Other example with `https://mangakakalot.com/read-ni5gp158524507166`

~~~
"W:/manga_py/base_classes/base.py:102:2020-05-05 19:12:02,157:Chapters list empty. Check https://mangakakalot.com/read-ni5gp158524507166"
No new chapters found
~~~

...

Maybe some [pathlib.WindowsPath](https://docs.python.org/3/library/pathlib.html?highlight=pathlib#pathlib.WindowsPath) in the program or a dependence. (?)

**Comment by 1271** [comment]
Unfortunately, I don’t even know how to get around this. This seems like a bug in docker.
The docker ideology speaks of isolation of the environment. Idk ¯\\_(ツ)_/¯

**Comment by 1271** [comment]
> Maybe some pathlib.WindowsPath in the program or a dependence. (?)

![изображение](https://user-images.githubusercontent.com/1452243/81145042-189fd280-8f7e-11ea-9002-a4cfbc8b2b1e.png)

It is true that `Path()` has a `WindowsPath` parent, but only `if os.name == 'nt'`

https://pathlib.readthedocs.io/en/pep428/

**Comment by gromenauer** [comment]
It's annoying, but only cosmetic (and really a minor issue).

**Comment by 1271** [comment]
I have an idea. Try to go into the docker container and run:

```bash
docker run -it --rm mangadl/manga-py python
```
```python
from pathlib import Path

Path('.').resolve()
```

**Comment by 1271** [comment]
Example for me:
![изображение](https://user-images.githubusercontent.com/1452243/81145952-04f56b80-8f80-11ea-9f9f-86ccf43a28b5.png)


Inside container:

![изображение](https://user-images.githubusercontent.com/1452243/81146299-b4cad900-8f80-11ea-93c6-85e58262bd07.png)

**Comment by 1271** [comment]
And... See this:

```
import os

os.name
```

**Comment by 1271** [comment]
And... See this:

```python
import os

os.name
```

**Comment by gromenauer** [comment]
~~~ bash
docker run -u 0:0 --interactive --tty --rm --name manga-py mangadl/manga-py /bin/bash 
root@edb5cd6706e4:/home/manga# python
Python 3.6.8 (default, May  4 2020, 18:00:16) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
~~~
~~~ py
>>> import os
>>> os.name
'posix'
>>> from pathlib import Path
>>> Path('.').resolve()
PosixPath('/home/manga')
~~~

**Comment by gromenauer** [comment]
In docker:
~~~ py
manga-py https://merakiscans.com/manga/my-wife-is-a-demon-queen/ --debug
~~~
~~~
"I:/manga_py/provider.py:89:2020-05-08 17:37:42,046:Manga name: my-wife-is-a-demon-queen"
"I:/manga_py/provider.py:90:2020-05-08 17:37:42,651:Content length 31687"
"W:/manga_py/base_classes/base.py:102:2020-05-08 17:37:43,270:Chapters list empty. Check https://merakiscans.com/manga/my-wife-is-a-demon-queen/"
"I:/manga_py/provider.py:92:2020-05-08 17:37:43,270:Chapters received (0)"
"I:/manga_py/provider.py:100:2020-05-08 17:37:43,270:User-agent: None"
No new chapters found
~~~

Some debugging later I really :facepalm: :roll_eyes: :rofl:  :

"PATH" | Real meaning
--- | ---
I: | Info
W: | Warning
E: | Error
