### ISSUE TITLE
BUG-Report (VIZ doesn't work anymore)

### ISSUE THREAD

**Issue by gitAXI** [manga-py/manga-py#295]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | 3.8.3rc1
Pip version | 19.2.3
Manga-py version | 1.19.3
URL | https://www.viz.com/shonenjump/one-piece-chapter-977/chapter/20349

Traceback (most recent call last):
  File "C:\Users\AXI\AppData\Local\Programs\Python\Python38\Scripts\manga-py-script.py", line 11, in <module>
    load_entry_point('manga-py==1.19.3', 'console_scripts', 'manga-py')()
    -> <function load_entry_point at 0x0000023097F72310>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x0000023098AD1700>
    -> <built-in function exit>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x0000023098AD15E0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x0000023098ACCDF0>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 46, in start
    raise e
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 30, in start
    self.parser.init_provider(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 37, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found

**Comment by 1271** [comment]
Sorry, viz.com is very limited supported. (Since the site does not work in my region (Russia), plus it requires a paid subscription to read all the chapters)

And.. Please, for any provider, use chapters list manga page. Example:

Not supported: https://www.viz.com/shonenjump/one-piece-chapter-977/chapter/20349
Supported: https://www.viz.com/shonenjump/chapters/one-piece

I’m not sure that someday full support for this site will appear. But this is entirely possible in the future.

Thank you for using manga-py

**Comment by 1271** [comment]
Support for viz was requested earlier (#184), but the author of the issue does not respond (it may have lost interest)
If you are willing to help with the development of a provider, I could try adding this.
But unfortunately I can’t promise it

**Comment by gitAXI** [comment]
No problem bro, VIZ is also restricted in my country, I’m using a vpn to get in the site and all mangas from there have the latest 3 chapters for free, I don’t know if I can help, since I don’t know codding at all (sorry xD), but if you need links, or something that can help you develop VIZ I can do it 👌

**Comment by 1271** [comment]
If you have a free plan, then thanks for trying. )
Free chapters are downloading now. But manga-py doesn't load paid chapters (and I don't know why)

**Comment by gitAXI** [comment]
I got this error when I tried to get a free chapter

**Comment by 1271** [comment]
I will try to check it out tomorrow. Thanks for issue

**Comment by gitAXI** [comment]
I also tried with jdownloader, but VIZ found  a way to crypt the images so I don’t know if it will still work with your script , anyway, thanks ❤️![image](https://user-images.githubusercontent.com/63649246/81227080-838bf080-8ff4-11ea-8fcf-acc0324ff469.jpeg)

**Comment by 1271** [comment]
Yes, manga-py decrypts the image matrix. (at least should: D)

**Comment by gitAXI** [comment]
That’s good to hear :D

**Comment by gitAXI** [comment]
Have you found a way to solve it? :D

**Comment by 1271** [comment]
Hi. Please expect this in the coming days. Thanks

**Comment by gitAXI** [comment]
Okay bro 💪

**Comment by gitAXI** [comment]
I got notified that you solved it, Can you give me an example of how you do it on VIZ? For me the same problem persists for a reason, I don’t know why

**Comment by 1271** [comment]
@gitAXI The fix is not yet in pip. Please check this after release. Thanks

**Comment by 1271** [comment]
@gitAXI check version `1.19.4`

**Comment by gitAXI** [comment]
@1271 
C:\Windows\system32>manga-py https://www.viz.com/shonenjump/one-punch-man-chapter-124/chapter/20484
"E:\manga_py\cli\__init__.py:38:2020-05-10 00:21:14,234:Please check if your inputed domain is supported by manga-py:
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "C:\Users\AXI\AppData\Local\Programs\Python\Python38\Scripts\manga-py-script.py", line 11, in <module>
    load_entry_point('manga-py==1.19.3', 'console_scripts', 'manga-py')()
    -> <function load_entry_point at 0x000002D8195B2310>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x000002D81A0F2700>
    -> <built-in function exit>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x000002D81A0F25E0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000002D81A10CE20>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 46, in start
    raise e
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 30, in start
    self.parser.init_provider(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 37, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found

**Comment by gitAXI** [comment]
I remind you that I updated the pip..

**Comment by 1271** [comment]
Please, read this: https://github.com/manga-py/manga-py/issues/295#issuecomment-624846316

**Comment by 1271** [comment]
You do not have to specify url address specific chapter

**Comment by gitAXI** [comment]
@1271 
C:\Windows\system32>manga-py https://www.viz.com/shonenjump/chapters/one-piece
Traceback (most recent call last):
  File "C:\Users\AXI\AppData\Local\Programs\Python\Python38\Scripts\manga-py-script.py", line 11, in <module>
    load_entry_point('manga-py==1.19.3', 'console_scripts', 'manga-py')()
    -> <function load_entry_point at 0x0000027099402310>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x0000027099F60700>
    -> <built-in function exit>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x0000027099F605E0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x0000027099F5CDC0>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 47, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x0000027099F5C910>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 49, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x0000027099F5CAF0>
    |                     -> <manga_py.parser.Parser object at 0x0000027099F5CAF0>
    -> <manga_py.parser.Parser object at 0x0000027099F5CAF0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 87, in process
    self.prepare_cookies()
    -> <manga_py.providers.viz_com.VizCom object at 0x000002709925EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\providers\viz_com.py", line 99, in prepare_cookies
    self.auth()
    -> <manga_py.providers.viz_com.VizCom object at 0x000002709925EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\providers\viz_com.py", line 110, in auth
    token = self.get_token()
            -> <manga_py.providers.viz_com.VizCom object at 0x000002709925EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\providers\viz_com.py", line 157, in get_token
    auth_token = self.http().get(auth_token_url, cookies=self.__cookies)
                 |               |                       -> <manga_py.providers.viz_com.VizCom object at 0x000002709925EBB0>
                 |               -> '/account/refresh_login_links'
                 -> <manga_py.providers.viz_com.VizCom object at 0x000002709925EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 106, in get
    response = self.requests(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 98, in requests
    self.response = self._requests_helper(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 69, in _requests_helper
    r = requests.request(method, url, **kwargs)
        |                |       |      -> {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.10...
        |                |       -> '/account/refresh_login_links'
        |                -> 'get'
        -> <module 'requests' from 'c:\\users\\axi\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\__init__.py'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           |                      |           |      -> {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.10...
           |                      |           -> '/account/refresh_login_links'
           |                      -> 'get'
           -> <requests.sessions.Session object at 0x000002709A17AEE0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
           |                    -> <Request [GET]>
           -> <requests.sessions.Session object at 0x000002709A17AEE0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
    |                |    -> OrderedDict()
    |                -> '/account/refresh_login_links'
    -> <PreparedRequest [GET]>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
          |             -> "Invalid URL '/account/refresh_login_links': No schema supplied. Perhaps you meant http:///account/refresh_login_links?"
          -> <class 'requests.exceptions.MissingSchema'>
requests.exceptions.MissingSchema: Invalid URL '/account/refresh_login_links': No schema supplied. Perhaps you meant http:///account/refresh_login_links?

**Comment by 1271** [comment]
`load_entry_point('manga-py==1.19.3', 'console_scripts', 'manga-py')()`

You have old manga-py version

try it:

```bash
pip install -U --no-cache manga-py

# OR specific version:

pip install manga-py==1.19.4
```

You can check current version:

```bash
manga-py --version
```

**Comment by 1271** [comment]
Only advice:
Judging by your log, you start cmd from the administrator. I highly advise against this.

**Comment by gitAXI** [comment]
@1271 
I did what you told me and it works somehow, many thanks <3, but there's one more thing, I used it, with login/pass (for viz) and this keeps going and won't stop :

[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}

**Comment by 1271** [comment]
Sorry, I can not help you with this, because don't have a viz account

**Comment by 1271** [comment]
Can you run manga-py with the --debug option and send the result here?

**Comment by 1271** [comment]
Just please check that your username / password does not get into the log

**Comment by gitAXI** [comment]
@1271 
C:\Windows\system32>manga-py --debug https://www.viz.com/shonenjump/chapters/one-piece
Login success
"I:\manga_py\provider.py:89:2020-05-10 01:13:52,214:Manga name: one-piece"
"I:\manga_py\provider.py:90:2020-05-10 01:13:53,052:Content length 3338954"
"I:\manga_py\providers\viz_com.py:57:2020-05-10 01:13:55,006:Chapters count: 978"
"I:\manga_py\provider.py:92:2020-05-10 01:13:55,031:Chapters received (978)"
"I:\manga_py\provider.py:103:2020-05-10 01:13:55,031:User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36""
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,032:Chapter idx: 4"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,032:Skip chapter 0 / https://www.viz.com/shonenjump/one-piece-chapter-4/chapter/5093?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,033:Chapter idx: 5"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,033:Skip chapter 1 / https://www.viz.com/shonenjump/one-piece-chapter-5/chapter/5094?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,034:Chapter idx: 6"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,034:Skip chapter 2 / https://www.viz.com/shonenjump/one-piece-chapter-6/chapter/5095?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,035:Chapter idx: 7"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,035:Skip chapter 3 / https://www.viz.com/shonenjump/one-piece-chapter-7/chapter/5096?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,036:Chapter idx: 8"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,036:Skip chapter 4 / https://www.viz.com/shonenjump/one-piece-chapter-8/chapter/5097?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,037:Chapter idx: 9"
"I:\manga_py\provider.py:134:2020-05-10 01:13:55,038:Skip chapter 5 / https://www.viz.com/shonenjump/one-piece-chapter-9/chapter/5155?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,038:Chapter idx: 10"
"I:\manga_py\provider.py:137:2020-05-10 01:13:55,039:Processed chapter 6 / https://www.viz.com/shonenjump/one-piece-chapter-10/chapter/5156?action=read"
"I:\manga_py\providers\viz_com.py:34:2020-05-10 01:13:55,039:Chapter idx: 10"
{"ok":0,"data":"no_auth"}
Traceback (most recent call last):
  File "C:\Users\AXI\AppData\Local\Programs\Python\Python38\Scripts\manga-py-script.py", line 11, in <module>
    load_entry_point('manga-py==1.19.4', 'console_scripts', 'manga-py')()
    -> <function load_entry_point at 0x0000017B34542310>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x0000017B350A2940>
    -> <built-in function exit>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x0000017B350A2820>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x0000017B3509EE50>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 47, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x0000017B3509E9A0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 59, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x0000017B3509EB80>
    |                     -> <manga_py.parser.Parser object at 0x0000017B3509EB80>
    -> <manga_py.parser.Parser object at 0x0000017B3509EB80>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 105, in process
    self.loop_chapters()
    -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 141, in loop_chapters
    self._download_chapter()
    -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 123, in _download_chapter
    raise e
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 118, in _download_chapter
    self._storage['files'] = self.get_files()
    |                        -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
    -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\providers\viz_com.py", line 76, in get_files
    self._metadata = loads(self.http_get(__url))
    |                |     -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
    |                -> <function loads at 0x0000017B349EBB80>
    -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\base_classes\base.py", line 74, in http_get
    return self.http().get(url=url, headers=headers, cookies=cookies)
           |                   |            |                -> None
           |                   |            -> None
           |                   -> '{"ok":0,"data":"no_auth"}'
           -> <manga_py.providers.viz_com.VizCom object at 0x0000017B3439EBB0>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 106, in get
    response = self.requests(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 98, in requests
    self.response = self._requests_helper(
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\manga_py\http\request.py", line 69, in _requests_helper
    r = requests.request(method, url, **kwargs)
        |                |       |      -> {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.10...
        |                |       -> '{"ok":0,"data":"no_auth"}'
        |                -> 'get'
        -> <module 'requests' from 'c:\\users\\axi\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\requests\\__init__.py'>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           |                      |           |      -> {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.10...
           |                      |           -> '{"ok":0,"data":"no_auth"}'
           |                      -> 'get'
           -> <requests.sessions.Session object at 0x0000017B3509EC70>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           |         |       -> {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           |         -> <PreparedRequest [GET]>
           -> <requests.sessions.Session object at 0x0000017B3509EC70>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 637, in send
    adapter = self.get_adapter(url=request.url)
              |                    -> <PreparedRequest [GET]>
              -> <requests.sessions.Session object at 0x0000017B3509EC70>
  File "c:\users\axi\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 728, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
          |                                                                 -> '{"ok":0,"data":"no_auth"}'
          -> <class 'requests.exceptions.InvalidSchema'>
requests.exceptions.InvalidSchema: No connection adapters were found for '{"ok":0,"data":"no_auth"}'

**Comment by 1271** [comment]
I know where the error is, but I'm not sure I can fix it. But I will try)
thank

**Comment by gitAXI** [comment]
No problem bro, You're not forced to do it hahaha

**Comment by 1271** [comment]
I do not do what I do not want.
But thanks for your care

**Comment by 1271** [comment]
Check updates:

```bash
pip install manga-py==1.19.5b0
```

If this does not work, then I can not help you.
At least until I get an account on viz.com
But it is very unlikely


P.S. 
You should also remember that manga-py does not have magic.
If you cannot get something in your browser, you cannot get it in manga-py

**Comment by gitAXI** [comment]
Many thanks, at first I got a few of:
"[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}"

Then the download started, and finished.. Sorry for bothering you and thanks for everything you've done :D

**Comment by 1271** [comment]
Sorry. I did not quite understand.
This does not works for you now? Or works?

**Comment by gitAXI** [comment]
It works perfectly 🤗, just that useless error at start which is nothing

**Comment by 1271** [comment]
OK. If everything is ok, then I close issue
If you have any questions, feel free to create a new issue

Thanks for using manga-py

**Comment by gitAXI** [comment]
@1271 
Hey, sorry for troubling you again mate, but here's something:
[InvalidSchema('No connection adapters were found for \'{"ok":0,"data":"no_auth"}\'')]
{"ok":0,"data":"no_auth"}

Is there any chance that they patched something this fast? It worked so nice today, but now this error keeps persisting for an unknown reason, if you need any help with an account or something I can give you my account, or I can make you one

**Comment by 1271** [comment]
The problem is not creating an account.
If you are logged in, manga-py expects that you have all the chapters available.
If some chapters are not available to you, they may not be downloaded or may have been downloaded with an error.

I do not have an account (as I said, the site is not available in my country).
But the problem is that most chapters are available only by subscription, which I see no reason to create and pay.

**Comment by gitAXI** [comment]
Umm.. okay, I understand. Thanks for your attention!

**Comment by gitAXI** [comment]
@1271 
(**In case someone has problems with this..**) I went with One Piece, and for like 10 minutes I got errors, till manga-py reached the point of those 3 free chapters and downloaded them.. So this script expects that you have all the chapters available as you said.. I think if you have a subscription, the script will take every chapter from that manga title. Also you have to use a VPN (ex. ProtonVPN, US/UK server, these are the fastest for me) and login on their website via browser, because the script doesn't get your login/pass if you're not logged in browser.

**Comment by 1271** [comment]
You can download only free chapters. To do this, you must not specify a username / password.

**Comment by 1271** [comment]
If you have already saved data for the site, you can delete the data.

See:

Linux:
`~/.PyMangaDownloader`
Windows:
`%AppData%\.PyMangaDownloader`

**Comment by gitAXI** [comment]
Nah, it doesn't work without login credentials, atleast for me :-?

**Comment by gitAXI** [comment]
@1271 
This happens when I try without login:
**"E:\manga_py\base_classes\archive.py:68:2020-05-11 21:27:36,435:Files list empty. Skip making archive"
https://d2vs6ffylckc3p.cloudfront.net/manga/shonenjump/onepiece/chapters/ONP01_5/metadata.json?Expires=1589221777&Signature=KWcVbTmyNZDAOOr0ovZvk-IHVUOJtkAbOGkN06poP9KRWr~rgZNsQ5ax096hKRymfF77~kqO8TaJkMGjyFC-NAkQq2pt-ATHVlQcRNKEcmTaag9DpFbFP4JIIkEjNxodK4GruKJCS9bsh3zYrnOS85mk0TlYlpPQMfKbpqOPWuFUqN8VkUSKlE2PD9Tq-MVdxc0Cevy5Hk8yyEE8JuUC6YuJzAvmPlDdIqmW7mvF1R0WUoF2p8lpsuXI7~s9vKXraaSvMfnwSNx2fafGg~StsT16kqt4y7DH8AUIydDSMPAPdUfqLMHyo9dhGBhNetgwR9QG-XYE2d7EjjF9xEJpxQ__&Key-Pair-Id=APKAJB4FLKRXY64XH6ZA
N/A% (0 of 250) |                                                                | Elapsed Time: 0:00:03 ETA:  --:--:--"E:\manga_py\providers\viz_com.py:235:2020-05-11 21:27:40,164:
URL is wrong:
 {"ok":0,"error":"invalid","data":"no_auth"}
"
"E:\manga_py\base_classes\archive.py:68:2020-05-11 21:27:44,611:Files list empty. Skip making archive"
https://d2vs6ffylckc3p.cloudfront.net/manga/shonenjump/onepiece/chapters/ONP01_6/metadata.json?Expires=1589221785&Signature=U1mKan5KlIzLHGNuroqi0HhhXyxsEa2ocwHClUDSOcqWwqhw9wI8CJHqN1UR6eOMuAE~3aPTv0tr6qrRLRuhvsJd-8jtdO08kqrhVopuAvYyLQY6YQc7J4vIjpxqysOaeRhp5V-Ami1JfJTzjEm8~mvCZYXYlBaLAk0bHqtLqgwQWJmgOWVCeU5E-MeACN79Kg5CwMw4nxl4VjX91A6PpvhHrFw3dO6GGI~i5-FdG~kCYjwJ1cLGdf4aarZGvW3AKkEmiF79WmBKcDSsD4WSkKp7mAxPHFE8xQ~d9bq~huGhQKc8XkNzGep~xn6DOnKSO~UkHK28e3KO0kJQEvpW1A__&Key-Pair-Id=APKAJB4FLKRXY64XH6ZA
N/A% (0 of 250) |                                                                | Elapsed Time: 0:00:12 ETA:  --:--:--"E:\manga_py\providers\viz_com.py:235:2020-05-11 21:28:12,152:
URL is wrong:
 {"ok":0,"error":"invalid","data":"no_auth"}
"
"E:\manga_py\base_classes\archive.py:68:2020-05-11 21:28:12,253:Files list empty. Skip making archive"
https://d2vs6ffylckc3p.cloudfront.net/manga/shonenjump/onepiece/chapters/ONP01_7/metadata.json?Expires=1589221813&Signature=lQgI4U5HFq37JbziAoMoXyD-2g4~Fsj9NnxmzOLmxex6q7DRqfZemDjYo05xzUlaYZUjbxT4Ehz4Mi3uD1Cn753PU1XABZUt1WSZOYb91QPe~NMNPxkim3losSAQAtl0zdNLeKTzXoMSndDYulQIceCrV-FAiKA-kvEabMzv1zIEixPdlanT3XqLrx0aqsRjXjXMmNOnE98QrppsTZYlb4645ka32pLutD2QGI2IXSfuka8~fVrid0WE23IANOQLxpG5R4Qv5dF6ut92c~qmJY4v6TWe~pSknHZIiTKtekF24XOCK6vpSUG9J5Hrf-s93oXdt1EZnWAuWEb~C5z-JA__&Key-Pair-Id=APKAJB4FLKRXY64XH6ZA
N/A% (0 of 250) |                                                                | Elapsed Time: 0:00:39 ETA:  --:--:--"E:\manga_py\providers\viz_com.py:235:2020-05-11 21:28:16,301:
URL is wrong:
 {"ok":0,"error":"invalid","data":"no_auth"}
"
"E:\manga_py\base_classes\archive.py:68:2020-05-11 21:28:16,402:Files list empty. Skip making archive"
https://d2vs6ffylckc3p.cloudfront.net/manga/shonenjump/onepiece/chapters/ONP01_8/metadata.json?Expires=1589221817&Signature=aA-GTloPPFDsjs93yztq10D7Bu~SZSY~Q7eRvbQjmoMqujUljTPlLMHbhmQLH1-mo7-XcaKtX13WIVrR6mD6CEQ1Rasz-KxfP60QXlYtQDm~yw4ERhElz9oMrEWdKjKbj8ZQKBji~86Mmut9KPgxP-iaPtJXaAUHvzk8eFM4RnOrEFHXjCLpfBGS8RpIfl9ysQfYqyti3cnSb2qW~RjAJCPEWQcvE7fQ6gmPsMZzpy42TIKpdCJPTzc9UcEPt016dmt-jHRnG2J2ZH1jmVYvUetZRapuKiHRX3QJ4wL5xP9RKGAlX9l0NPxMHZ1gEy4bVAfLKwb-FMN4g2pG8uFFdA__&Key-Pair-Id=APKAJB4FLKRXY64XH6ZA
N/A% (0 of 250) |                                                                | Elapsed Time: 0:00:43 ETA:  --:--:--"E:\manga_py\providers\viz_com.py:235:2020-05-11 21:28:20,095:
URL is wrong:
 {"ok":0,"error":"invalid","data":"no_auth"}**

**Comment by 1271** [comment]
Then I'm sorry, I'm not sure I can help.
Debugging viz is very difficult.
In any case, viz.com will not be supported in version 2.0, unless someone else does it.

**Comment by gitAXI** [comment]
@1271 
Yeah, you should give up on it, they're always changing/patching things in their website, it's useless to continue this. Wish you a good evening!

**Comment by 1271** [comment]
The problem is not the change.  Just viz is a very problematic site due to country restrictions

**Comment by gitAXI** [comment]
Yeah, that also... It's weird even after all these years they didn't remove those restrictions for most of the countries from around the world

**Comment by TAAPArthur** [comment]
With version 1.19.7, viz seems to work fine at least in the U.S.
`manga-py -c 1 https://www.viz.com/shonenjump/chapters/one-piece`
Was able to login in and reach chapter 4 of One Piece (first non-free chapter).
