### ISSUE TITLE
GMANGA not working 

### ISSUE THREAD

**Issue by Bomrzoq** [manga-py/manga-py#296]
# Bug report
Environment (please complete the following information):

Description | Data
This site is not working it gives me that there are no new chapters |---
OS | Windows 10
Python version | 3.8

**Comment by 1271** [comment]
Site down for me
![image](https://user-images.githubusercontent.com/1452243/81310129-630f7500-908c-11ea-9f38-c2d229a9805e.png)


P.S. 
Please remember that developers cannot guess what exactly does not work for you.
You will seem more responsible if you describe the error more fully.

**Comment by 1271** [comment]
https://github.com/manga-py/manga-py/issues/322#issuecomment-663951891
