### ISSUE TITLE
Bug and/or redirection: mangabat.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#297]
# Bug report
Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.3
URL | `https://mangabat.com/manga/serie-1088913029`

#### To Reproduce:
~~~ bash
docker run --interactive --tty --rm --name manga-py \
   -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://mangabat.com/manga/serie-1088913029
~~~

#### Additional context
Output: 
~~~
[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
...
~~~

But `https://mangabat.com/manga/serie-1088913029` is redirected to `https://m.mangabat.com/read-gb384720`

~~~ bash
manga-py https://m.mangabat.com/read-gb384720
...
AttributeError: Provider not found
~~~

**Comment by gromenauer** [comment]
OOps! misplaced comment:
___

> 
> In #299 I put what seems the right regexp to be there. But don't always solves the problem.
> 
> I don't know how to get images form second server. 
> 
> Example where regexp works: 
> 
> Chapter: `https://mangakakalot.com/chapter/dz919342/chapter_1`
> When you click `https://mangakakalot.com/change_content_s2` images change in this way:
> ~~~
> 1: https://s5.mkklcdnv5.com/   mangakakalot/d2/dz919342/chapter_1/1.jpg
> 2: https://bu2.mkklcdnbuv1.com/mangakakalot/d2/dz919342/chapter_1/1.jpg
> ~~~
> 
> Example where regexp don't works:
> 
> Chapter: `https://mangakakalot.com/chapter/cd919002/chapter_0`
> When you click `https://mangakakalot.com/change_content_s2` images change in this way:
> ~~~
> 1: https://s41.mkklcdnv41.com/ mangakakalot/c1/cd919002           /vol1_chapter_0_metropolitan_system_prologue/1.jpg
> 2: https://bu2.mkklcdnbuv1.com/mangakakalot/m1/metropolitan_system/vol1_chapter_0_metropolitan_system_prologue/1.jpg
> ~~~

**Comment by 1271** [comment]
Redesign on the site.
I will update the provider soon

**Comment by gromenauer** [comment]
Maybe a "bug::redesigned_site" github label is handy for this?

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.4
URL | `https://mangabat.com/manga/serie-1088913029`
URL | `https://m.mangabat.com/read-gb384720`

**Comment by 1271** [comment]
> Maybe a "bug::redesigned_site" github label is handy for this?

Let it remain just a bug :D
