### ISSUE TITLE
➕ Request to add: reaperscans.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#302]
# Request to add a site

Description | Data
---|---
Url to add | `https://reaperscans.com`

:sunglasses: `--force-provider https://zeroscans.com/` Works! :tada: 

Example:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.5
URL | `https://reaperscans.com/comics/58193-dimensional-mercenary`

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://reaperscans.com/comics/58193-dimensional-mercenary \
    --force-provider https://zeroscans.com/comics/636122-hero-i-quit-a-long-time-ago
~~~

**Comment by 1271** [comment]
Check updates

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.6
URL | `https://reaperscans.com/comics/58193-dimensional-mercenary`
