### ISSUE TITLE
✨ Show where "Go to random site" in https://manga-py.com/manga-py/ will go.

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#306]
# ✨ Feature request

Show where "Go to random site" in https://manga-py.com/manga-py/ will go.

**Is your feature request related to a problem? Please describe.**
I clicked "Go to random site" in https://manga-py.com/manga-py/ button, a tab opens, but only `about:blank` is showed. ... :thinking: what url is failing to report it ?

**Describe the solution you'd like**
Make "Go to random site" button of https://manga-py.com/manga-py/ show where is it going. Example: Add `<p> Last random site opened: https://isekaiscan.com/ </p>` below the button.

**Describe alternatives you've considered**
:shrug: 

**Additional context**
:speech_balloon:

**Comment by 1271** [comment]
OK. It's not difficult. Do a little bit later

**Comment by 1271** [comment]
Please, check it 😄

**Comment by gromenauer** [comment]
Works OK :+1: 

But a lot off sites seems to be down:

- http://mangabb.co/
- https://otakusmash.com/
- https://reader.shoujosense.com/
- https://reader.imangascans.org/
- https://mangahasu.se/

Could it be my connection? Web pandemic ? :microbe:

**Comment by 1271** [comment]
> Web pandemic ?

Most likely the site is not needed by the owner. This happens. (I will remove these providers soon)

**Comment by 1271** [comment]
P.S. I am surprised that this is otakusmash
