### ISSUE TITLE
False positive "Manga url changed!"

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#307]
# Bug report

In every use of any web, it fires "Manga url changed!" warning, but the url it shows it's the same.

Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.8
URL | `https://manganelo.com/manga/ernak`

#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages \
    --no-webp --show-current-chapter-info \
    https://manganelo.com/manga/ernak -c 3
~~~

#### Additional context
Output:
~~~
"WARNING:/manga_py/parser.py:51:2020-06-06 16:53:17,597:Manga url changed! New url: https://manganelo.com/manga/ernak"


Current chapter url: https://manganelo.com/chapter/ernak/chapter_4
...
~~~

**Comment by 1271** [comment]
Yeah. Updated just
Please, check new version 😄

**Comment by gromenauer** [comment]
Warning gone :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.9
URL | `https://manganelo.com/manga/ernak`
