### ISSUE TITLE
manhwa.club

### ISSUE THREAD

**Issue by hello802** [manga-py/manga-py#308]
# Request to add a site

Description | Data
---|---
Url to add | https://manhwa.club/manhwa/perfect-half/

**Comment by 1271** [comment]
Check for updates after 15 minutes

**Comment by 1271** [comment]
Hello. It's worked?
If everything is ok, please close this issue.

**Comment by gromenauer** [comment]
Works for me :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.2
URL | `https://manhwa.club/manhwa/perfect-half/`

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
