### ISSUE TITLE
Provide docker image for others architecture

### ISSUE THREAD

**Issue by wilfriedroset** [manga-py/manga-py#309]
# Feature request

**Is your feature request related to a problem? Please describe.**
I would like to use manga-py using docker on a raspberrypi 3 B+. The current image [mangadl/manga-py](https://hub.docker.com/r/mangadl/manga-py) is only for linux/amd64 which makes it unusable.

**Describe the solution you'd like**
Update the image published on hub.docker.com to support others architectures (in my case I would like armv7l). The current image is based on [debian:buster-slim](https://hub.docker.com/_/debian?tab=tags&page=1&name=buster) which support many architectures.

**Describe alternatives you've considered**
I can think of 3 alternatives solutions:
* local build 
* create another image on hub.docker.com to support others architectures
* install manga-py directly on the rpi using `pip install`

**Additional context**
Here is the result of docker info on a rpi 3 B+
```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 2
  Paused: 0
  Stopped: 7
 Images: 31
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.118-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 975.6MiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
docker version
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e6
 Built:             Mon Jun  1 09:23:23 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e6
  Built:            Mon Jun  1 09:17:17 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
debian_version
```
$ cat /etc/debian_version
10.4
```

Installing manga-py from pypi on rpi get stuck if you don't have installed the following lib (tried on python:3 image to avoid installing python manually)
```
root@fc97e9a19f0c:/# history
    1  apt update
    2  apt-get install -y python3-lxml apt install libxml2-dev libxslt-dev python3-dev
    3  pip install manga-py
```

Here a quick example
```
from python:3

ENV LANG C.UTF-8
RUN apt-get update \
  && apt-get install -qy --no-install-recommends \
    python3-lxml \
    libxml2-dev \
    libxslt-dev \
    python3-dev \
  && pip install -q manga-py
```

I reckon that it might be necessary to add them to the dockerfile

**Comment by 1271** [comment]
Thanks for the suggestion. Will be in the next release.

**Comment by 1271** [comment]
@wilfriedroset  please, check latest docker build
`docker push mangadl/manga-py:latest`
Now manga-py Docker is based on a standard python image

**Comment by wilfriedroset** [comment]
According to hub.docker.com [the latest image ](https://hub.docker.com/layers/mangadl/manga-py/latest/images/sha256-4052a47d400bc870c1eab373ebafc0d5ddafb13b5241efd9fcdba74ae2461fb3?context=explore) is meant for `OS/ARCH: linux/amd64` which will not work on rpi3.

Example
```
~ $ docker pull mangadl/manga-py:latest
latest: Pulling from mangadl/manga-py
81fc19181915: Pull complete
ee49ee6a23d1: Pull complete
828510924538: Pull complete
a8f58c4fcca0: Pull complete
33699d7df21e: Pull complete
050568a16812: Pull complete
b3a91168a5ae: Pull complete
e851455523ff: Pull complete
0bdd0efffdcc: Pull complete
820966ff4995: Pull complete
4e540591d63a: Pull complete
2d642ae41a97: Pull complete
e50e7e8ced94: Pull complete
7683526033b4: Pull complete
Digest: sha256:4052a47d400bc870c1eab373ebafc0d5ddafb13b5241efd9fcdba74ae2461fb3
Status: Downloaded newer image for mangadl/manga-py:latest
docker.io/mangadl/manga-py:latest
~ $ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
mangadl/manga-py          latest              7a884355fb16        12 hours ago        1.12GB
~ $ docker run -it mangadl/manga-py --help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--help\": executable file not found in $PATH": unknown.
```

As expected the pull is correct but the image is not usable.

**Comment by 1271** [comment]
Oh ... you are right. I will try to come up with something. thanks

P.S. 
Have you tried using the docker file directly from the repository? This should work (I hope)

```bash
curl https://raw.githubusercontent.com/manga-py/manga-py/stable_1.x/helpers/python/Dockerfile -O && docker build - < Dockerfile
```

At least for the time being, this does not work for you from the repository

**Comment by 1271** [comment]
@wilfriedroset 
Please, check latest docker version

**Comment by wilfriedroset** [comment]
Looks good to me
```
~ $ docker images | grep manga-py
mangadl/manga-py          latest              61892bba4fd9        17 hours ago        551MB
~ $ docker run -it mangadl/manga-py manga-py -v
1.19.13
```

**Comment by 1271** [comment]
Cool. It remains to figure out how to run builds automatically :rofl:

**Comment by wilfriedroset** [comment]
Seems like something you might want to try https://www.docker.com/blog/multi-arch-build-what-about-travis/

**Comment by 1271** [comment]
Thanks for the help.

**Comment by 1271** [comment]
I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
