### ISSUE TITLE
can't download from nhentai.net

### ISSUE THREAD

**Issue by ShinoIro** [manga-py/manga-py#310]
# Bug report
C:\Users\Shi.no.iro\Documents>manga-py https://nhentai.net/g/261062/ -d D:/Manga/Mi
[AttributeError("'NoneType' object has no attribute 'group'")]

C:\Users\Shi.no.iro\Documents>manga-py https://nhentai.net/g/237576/ -d D:/Manga/Mi
[AttributeError("'NoneType' object has no attribute 'group'")]

Description | Data
---|---
OS | Windows 10
Python version | 3.8.2
Pip version | 20.1.1
Manga-py version | 1.19.10
URL | https://nhentai.net/g/*/ (any on this site)

I hope my description is detailed enough.. And i hope it's fixed soon..
Thank you
"Abandon all hope, ye who enter here
ここから入らんとする者は一切の希望を放棄せよ "
-nhentai login page

**Comment by ShinoIro** [comment]
if you need more detail, email here:
rohmat.cadangan@gmail.com

**Comment by 1271** [comment]
Fixed. Will be with the next release
Thanks for issue

**Comment by ShinoIro** [comment]
damn that was fast, thanks for the fix..

**Comment by 1271** [comment]
It was not difficult. Wait for the update on sunday.
Thank you for using manga-py

**Comment by 1271** [comment]
@ShinoIro Check version 1.19.11

**Comment by 1271** [comment]
Hello. It's worked?
If everything is ok, please close this issue.

**Comment by gromenauer** [comment]
Works OK for me :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.2
URL | `https://nhentai.net/g/261062/`

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
