### ISSUE TITLE
Connection aborted and Read timeouts when downloading from mangadex.org

### ISSUE THREAD

**Issue by XantherBanter** [manga-py/manga-py#314]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Ubuntu 18.04 LTS
Python version | 3.6.9
Pip version | 9.0.3
Manga-py version | 1.19.12
URL | https://mangadex.org/*

#### To Reproduce:
1. Download any manga from mangadex
2. During download, error spams the following then it continues downloading current chapter

`ERROR:/manga_py/http/__init__.py:68:2020-06-15 18:33:41,834:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"`
`ERROR:/manga_py/http/__init__.py:68:2020-06-15 18:34:11,480:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"`
`"ERROR:/manga_py/http/__init__.py:68:2020-06-15 19:09:12,584:HTTPSConnectionPool(host='hd5ze167xfjda.za7a56fpsknn8.mangadex.network', port=443): Read timed out. (read timeout=60)"`

#### Additional context
App is running under pipx on a headless machine on Hetzner. Suspected throttling server-side, probs detected that I'm on a datacenter IP. Tried adding chrome user agent with same results. Might help if there's an option to sleep after each chapter downloaded. Yet to try other other sites.

**Comment by 1271** [comment]
It's a problem of your internet provider and/or mangadex
Sorry, I can’t help you with anything.
Try this again at a different time. Maybe it will work.

**Comment by gromenauer** [comment]
Works for me 🤷

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.12
URL | `https://mangadex.org/title/36646/the-swordsman-called-the-countless-swords-sorcerer`
Language | gb

**Comment by gromenauer** [comment]
Only the created directory name is strange: `The Swordsman Called the Countless Swords&rsquo; Sorcerer`

**Comment by 1271** [comment]
Special characters are not unescaped.

I’m not sure that it’s worth changing this behavior now, because old manga versions will be downloaded again if someone automatically gets new chapters

**Comment by gromenauer** [comment]
My downloads are scripted with `--name` to retain the name of the folder. No problem for me to have strange names or to have new names.

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
