### ISSUE TITLE
OpenSSL deprecated in last docker image

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#316]
# Bug report
Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 9 (stretch)
Python version | Python 3.7.8
Pip version | pip 20.1.1 
Npm version | 6.14.5
Manga-py version | 1.19.13

#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py mangadl/manga-py manga-py  --version
~~~

#### Additional context

Output:

~~~
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) 
does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 
required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
~~~

**Comment by gromenauer** [comment]
#309 related?

**Comment by 1271** [comment]
> #309 related?

Yeah... In the near future I will try to configure the image build on my vps.
Please use pip version of manga-py soon

**Comment by 1271** [comment]
Please, check latest docker version
