### ISSUE TITLE
Add 'Powered by Genkan' sites (using provider reaperscans.com)

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#317]
# Request to add a site

Both work with `--force-provider https://reaperscans.com/comics/58193-dimensional-mercenary` (and seems that all sites saying 'Powered by Genkan' will too)

Description | Data
---|---
Url to add | `https://secretscans.co`
Url to add | `https://kkjscans.co`

Works using provider `reaperscans.com`

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 9 (stretch)
Python version | Python 3.7.8
Pip version | pip 20.1.1 
Npm version | 6.14.5
Manga-py version | 1.19.13
URL | `https://secretscans.co/comics/974615-the-god-of-death`
URL | `https://kkjscans.co/comics/51329-gokufuri-kyohi-shite-tesaguri-start-tokka-shinai-healer-nakama-to-wakarete-tabi-ni-deru`
     
Worked with:

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://secretscans.co/comics/974615-the-god-of-death \
    --force-provider https://reaperscans.com/comics/58193-dimensional-mercenary
~~~ 

Output:
~~~
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.


Current chapter url: https://secretscans.co/comics/974615-the-god-of-death/1/1

100% (6 of 6) |##############| Elapsed Time: 0:00:04 Time:  0:00:04

~~~

**Comment by gromenauer** [comment]
Other site 'Powered by Genkan':

`https://edelgardescans.com/comics/696728-solo-login`

**Comment by gromenauer** [comment]
More:
* `https://hunlight-scans.info/comics/320101-reader`
* `https://hatigarmscanz.net/comics/646915-the-skeleton-soldier-couldnt-protect-the-dungeon` (redirection of `http://hatigarmscans.net`)
* `https://the-nonames.com/comics/790284-tensei-kizoku-no-isekai-boukenroku-jichou-wo-shiranai-kamigami-no-shito`
* `https://methodscans.com/comics/773532-meng-shi-zai-shang`

**Comment by gromenauer** [comment]
leviatanscans.com have it's own provider. Maybe it could be unified in a "genkan" provider.

**Comment by 1271** [comment]
Okay :smile: 
Thanks for issue

**Comment by gromenauer** [comment]
Docker generation failed, unable to test, sorry.

**Comment by 1271** [comment]
An error occurred while generating the image. Please try now

**Comment by gromenauer** [comment]
Oops! No manga-py

``` bash
docker run mangadl/manga-py
docker: Error response from daemon: linux spec user: unable to find user manga: no matching entries in passwd file.
ERRO[0000] error waiting for container: context canceled 

```

**Comment by 1271** [comment]
Hmmm...

**Comment by 1271** [comment]
![изображение](https://user-images.githubusercontent.com/1452243/88531552-b1893b80-d00b-11ea-857a-aa572905f5e6.png)

**Comment by 1271** [comment]
<details>
<summary>Sorry, just thinking out loud.</summary>
<br>
Don't really understand people who use docker.<br>
In very complex projects, this is justified, but installing an entire OS instead of installing one project - I will never understand this.<br>
This is similar to the need to install 500+ javascript packages in order to make 1 html page.
</details>

**Comment by gromenauer** [comment]
My bad :innocent: 
Removed docker image + run again → OK :+1: 
(... but have yet to test the issue)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.19.14
URL | `https://secretscans.co/comics/974615-the-god-of-death`
URL | `https://kkjscans.co/comics/51329-gokufuri-kyohi-shite-tesaguri-start-tokka-shinai-healer-nakama-to-wakarete-tabi-ni-deru`
URL | `https://hunlight-scans.info/comics/320101-reader`
URL | `https://hatigarmscanz.net/comics/646915-the-skeleton-soldier-couldnt-protect-the-dungeon`
URL | `https://the-nonames.com/comics/790284-tensei-kizoku-no-isekai-boukenroku-jichou-wo-shiranai-kamigami-no-shito`
URL | `https://edelgardescans.com/comics/696728-solo-login`
URL | `https://methodscans.com/comics/773532-meng-shi-zai-shang`
