### ISSUE TITLE
no npm in docker 

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#318]
# Bug report
Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | :scream: 
Manga-py version | 1.19.13

#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py mangadl/manga-py /bin/bash
manga@930c6733b0fa:~$ npm --version
~~~

#### Additional context
Output:

~~~
bash: npm: command not found
~~~

**Comment by gromenauer** [comment]
Tried to download `https://leviatanscans.com/comics/i-am-the-sorcerer-king` and didn't work, maybe `npm` is the cause.

**Comment by gromenauer** [comment]
apt install npm into docker don't fix leviatanscans :/

**Comment by 1271** [comment]
Hmm .. in docker image nodejs is present.
Thanks for the issue, I will fix it soon.

**Comment by gromenauer** [comment]
Is the previous docker version available (as a backup plan)?

**Comment by 1271** [comment]
Please give me a couple more days. I finally found some free time and will soon be back to work on manga-py
I will have a little vacation 😄

**Comment by 1271** [comment]
https://github.com/manga-py/manga-py/issues/322#issuecomment-663951891
