### ISSUE TITLE
🙈 Silent fail when no npm

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#320]
# Bug report

Related to #318 
When no `npm` in the system and is needed to operate, a specific Warning or Error should be thrown.
Return an exit status != 0 of the script, when a error or warning occurs, helps automation.

Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version |  :scream: 
Manga-py version | 1.19.13
URL | `https://bato.to/series/79305`

#### To Reproduce:

~~~ bash
manga-py https://bato.to/series/79305
~~~

#### Additional context

Output
~~~ bash
"WARNING:/manga_py/base_classes/base.py:103:2020-07-11 10:40:50,587:Chapters list empty. Check https://bato.to/series/79305"
No new chapters found
~~~

Warning that no npm is available will be good
Exit status != 0 will be great :smile:

**Comment by 1271** [comment]
@gromenauer see https://github.com/manga-py/manga-py/issues/322#issuecomment-663951891

**Comment by gromenauer** [comment]
I should move the issue to cloudscraper instead.

**Comment by 1271** [comment]
Not sure if VeNoMouS will do this for free.
Anyway, it's his choice
