### ISSUE TITLE
lock file when trying to run the same command

### ISSUE THREAD

**Issue by phanirithvij** [manga-py/manga-py#323]
# Feature request

**Is your feature request related to a problem? Please describe.**
When I run something like (I don't know the exact cli options but)

```
manga-py "URL" -start s -end e
```

If I run exactly the above command in two terminals then the one that is run the second time will try to download from the start itself and disturbs the other command which has already downloaded more images.

**Describe the solution you'd like**
One way to prevent this is to hash the whole command and store a lock file with the name "hash.lock" in the destination directory and before cleanup delete the lock file.

And when the same command is run we must prompt that the same command is already running and this is not intended.

**Describe alternatives you've considered**
Another alternative is to see if there are any conflicting downloads already running using a database or some filesystem cache which requires more changes to the code.

**Additional context**
I think it will be useful because manga-py for me on windows doesn't get interrupted no matter how I try and kill it.

**Comment by 1271** [comment]
Oh .. I'll think about what can I do about it

**Comment by 1271** [comment]
Fixed :D
manga-py now interrupted 😇
