### ISSUE TITLE
http://mangaseeonline.us redirects to https://mangasee123.com/

### ISSUE THREAD

**Issue by wahab14131211** [manga-py/manga-py#325]
You can see the error if you run: /usr/local/bin/manga-py https://mangaseeonline.us/manga/Solo-Leveling 

Although this is not specific to my machine, i am running manga-py on a raspberry pi 4 with python 3.8.2 and manga-py version 1.19.15.

Please let me know if you need any other information from me.

**Comment by 1271** [comment]
I will try to fix it soon

**Comment by 1271** [comment]
Please, update manga-py and use new url

**Comment by gromenauer** [comment]
:bug: `raise AttributeError('Provider not found')`

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.2
URL | `https://mangaseeonline.us/manga/Solo-Leveling`

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD/:/home/manga/Manga \
  --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga \
    --cbz --zero-fill --rename-pages --no-webp \
    --show-current-chapter-info \
    https://mangaseeonline.us/manga/Solo-Leveling \
    -c 3
~~~
~~~ py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.20.2', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7f979767b9d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f9791c50730>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f9791c50620>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f9791c49ac8>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 46, in start
    raise e
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 35, in start
    info=self._info,
         └ <manga_py.cli.Cli object at 0x7f9791c49a90>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 41, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found
~~~

**Comment by wahab14131211** [comment]
Just changed the url and tested it. It seem so be working on my end.
Thanks for the quick fix!

**Comment by wahab14131211** [comment]
Hello again,

I have run into an issue with mangasee123. 
I cannot download any chapter after 78 in the tower of god manga on this website. i get the following error: "ERROR:/manga_py/provider.py:158:2020-07-30 19:39:27,325:Error processing file: Tower_of_God-vol_272"

The command i am running is: /usr/local/bin/manga-py https://mangasee123.com/manga/Tower-Of-God (you need to wait a bit for the first 78 chapters to download)

i am running v1.20.2 of manga-py

**Comment by 1271** [comment]
@gromenauer 
> AttributeError: Provider not found

Yeah. Old url not supported now.


@wahab14131211
Thanks, i check it.
