### ISSUE TITLE
add site https://18comic.org/

### ISSUE THREAD

**Issue by tienok2004** [manga-py/manga-py#331]
# Request to add a site

Description | Data
---|---
Url to add | https://18comic.org/

**Comment by 1271** [comment]
Sorry for the long wait.

There may be a problem with this site. The point is that the images on the preview page are very small. (see attachment)

I'm not sure that this option will suit, but everything downloaded will be in the archive.
I'm not sure if I can glue these images together correctly (this will result in one very long one)

![изображение](https://user-images.githubusercontent.com/1452243/91656722-95bdfd00-eac3-11ea-9bd4-6f652ada2224.png)
![изображение](https://user-images.githubusercontent.com/1452243/91656737-ab332700-eac3-11ea-8f5b-485ae3d13e75.png)

But some are bigger than others:
![изображение](https://user-images.githubusercontent.com/1452243/91656753-caca4f80-eac3-11ea-8f50-377feef6313a.png)

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
