### ISSUE TITLE
unable to process chapter due to multiple seasons mangasee123.com

### ISSUE THREAD

**Issue by bgkillas** [manga-py/manga-py#339]
URL | https://mangasee123.com/manga/Tower-Of-God
if you use manga py with any multiple season manga it seems to get confused

**Comment by 1271** [comment]
Ok, I'll fix it today. Thanks for the issue

**Comment by 1271** [comment]
Sorry for the long wait. The problem has been resolved, an update will be ready soon

**Comment by 1271** [comment]
Check version 1.22.1
