### ISSUE TITLE
I am stupid??

### ISSUE THREAD

**Issue by Sblop** [manga-py/manga-py#341]
I cant make this work...

docker run -it mangadl/manga-py "manga-py http://xxx.com/manga/xxx"

What am I doing wrong? I also tried running it through docker, but I cant get past the "version" number it keeps writing, before the container stops...

When running:

docker run -it mangadl/manga-py "manga-py -h"

I correctly get the help message...

**Comment by 1271** [comment]
You are not stupid. ^_^

Try it:
`docker run -it mangadl/manga-py http://xxx.com/manga/xxx`

**Comment by 1271** [comment]
As you can see, the default docker file entry point is manga-py
Those. you don't need to duplicate this

https://github.com/manga-py/manga-py/blob/625ff6128c40fd034d92e49f70cd37a090ce02bd/helpers/Dockerfile#L30

**Comment by Sblop** [comment]
Thanks so much. Now it Works.
