### ISSUE TITLE
Add the possibility to save the chapter info in a JSON file

### ISSUE THREAD

**Issue by eduhoribe** [manga-py/manga-py#344]
# Feature request

Very similar to the option `--show-current-chapter-info`, but saving that information in a file like `info.json`

**Comment by eduhoribe** [comment]
I have already implemented, but I can't push the changes to a new branch and make a pull request

**Comment by gromenauer** [comment]
You have to fork it to be able to make a pull request.

**Comment by eduhoribe** [comment]
There is a preferred branch to make the changes?

**Comment by 1271** [comment]
Merged. Thanks

**Comment by eduhoribe** [comment]
Can o close this issue? It will interfere in the project workflow somehow?

**Comment by 1271** [comment]
No, it's not. Thanks for your work!

**Comment by eduhoribe** [comment]
Glad to help :smile:
