### ISSUE TITLE
Serimanga

### ISSUE THREAD

**Issue by ghost** [manga-py/manga-py#346]
# Request to add a site

Description | Data
---|--- 
I guess this app does not support many turkish manga website, so if you would add this biggest turkish manga website, it would be ok i guess :D | https://serimanga.com/

**Comment by 1271** [comment]
Any wishes. If i can, be sure to add. Thanks for the issue

**Comment by 1271** [comment]
Check updates

**Comment by ghost** [comment]
it works, thanks for your work.
