### ISSUE TITLE
Add the possibility to save the manga info in a JSON file

### ISSUE THREAD

**Issue by eduhoribe** [manga-py/manga-py#347]
# Feature request

Very similar to the option `--show-current-chapter-info` and `--save-current-chapter-info`, but saving the manga information (instead of the chapter information) in the root of the download folder.

Ex.:
```
...
  /Download
    /MangaName
      vol_000.zip
      vol_001.zip
      .
      .
      .
      vol_00N.zip
      info.json
```

## Worries

* Maybe not all providers today are capable of getting the comic information.
* For the providers who can get comic info, the return of the content may not be regular.
* The suggested file path may not be appropriated

**Comment by 1271** [comment]
I think this is not a problem.
Thanks for the issue

**Comment by 1271** [comment]
I renamed info.json to eduhoribe.json and returned the old version info.json (it is used in at least 1 project)

Check it for version `manga-py=1.23.0`

**Comment by eduhoribe** [comment]
Nice, thanks.
The implementation of this feature in other providers will be in a different issue?

**Comment by 1271** [comment]
At your discretion. In general, this is the same functionality, we can use this one, I think

**Comment by eduhoribe** [comment]
I think the same way

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
