### ISSUE TITLE
Error processing file: -vol_00x-English mangadex.org

### ISSUE THREAD

**Issue by tremofox** [manga-py/manga-py#349]
#Bug report
Environment (please complete the following information):
I'm getting "ERROR:\manga_py\provider.py:163:2020-11-12 18:01:36,971:Error processing file: -vol_00x-English" with a couple links from MangaDex

Description | Data
---|---
OS | Windows 10
Python version | 3.6.5
Pip version | 9.0.1
Manga-py version | 1.3.29.1
URL |https://mangadex.org/title/33977/the-vertical-world

#### To Reproduce:
manga-py https://mangadex.org/title/33977/the-vertical-world -N -d ./Jump+ --arguments language=gb
(also happens with https://mangadex.org/title/35870/heart-gear)

**Comment by 1271** [comment]
This is not a bug.
![изображение](https://user-images.githubusercontent.com/1452243/99039218-0390a580-2598-11eb-89c8-2d886a7b0ff0.png)
