### ISSUE TITLE
--proxy is not applied for get request in check_url

### ISSUE THREAD

**Issue by ZeeWanderer** [manga-py/manga-py#353]
# Bug report

Description | Data
---|---
OS|Windows 10
Python version | 3.9.0
Pip version | 20.3.1
Manga-py version | stable_1.x latest commit
URL | https://mangadex.org/title/37498/kimi-wa-houkago-insomnia

Here https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/parser.py#L65 proxies from `--proxy` option are not applied so if the URL is unreachable without proxy then check is not passed. Very strange oversight. 
If I modify code to use a specific proxy in this check then further steps work as intended with args specified proxy.

**Comment by 1271** [comment]
Oh, you're right. Thanks, this will be fixed today.
Thanks for issue

**Comment by 1271** [comment]
Please, check version `1.24.1`
`pip install -U manga-py`

**Comment by ZeeWanderer** [comment]
`1.24.1` fixes the issue
