### ISSUE TITLE
Consistent IMAGES_SKIP_ERROR due to specific files

### ISSUE THREAD

**Issue by tgaugry** [manga-py/manga-py#355]
Hello,
I am currently using the latest version (1.24.2) and i get consistent and reproductible errors while downloading specific chapter. It is always due to the same image, so I assume something is misbehaving aroung `MangaImage.is_image`.

To reproduce: `manga-py -s 26 -c 1 --debug https://manganelo.com/chapter/1000_yen_hero`
On this example, it always produce an error on `001_2.jpg`
`"WARNING:/manga_py/base_classes/archive.py:55:2020-12-23 01:01:58,508:File "/tmp/.PyMangaDownloader/temp_90371/001_2.jpg" isn't image"`

This produce a file `Manga/1000_yen_hero/vol_026.IMAGES_SKIP_ERROR.zip` without said image.
This specific image seems to load fine on the regular website... Any idea ?

I also noticed that there is no mention of this error on the returned `Info`object; is this intended ?
Thanks

**Comment by 1271** [comment]
Hi. The image is also missing on the site (it does not exist) (Red line)
![image](https://user-images.githubusercontent.com/1452243/102967961-1639bb00-4504-11eb-91c7-88240ce4a5b1.png)

Error chapter information should go to json dump. (i wil check it)

Hmm ... you are right, the error does not get into the json report. I'll be correct it soon, thanks :+1:

**Comment by tgaugry** [comment]
Ok, it seems to be due to the image source. Looking at my logs, it download from `s71.mkklcdnv7.com`. Browser goes to `bu3.mkklcdnbuv1.com` (which also doesn't work anymore :( ... I imagine i accessed a third one yesterday).

So if i want to use manga-py as a lib, i'm supposed to use the resulting json, and not the Info class ?

Edit: nvm, json is generated from the Info class -> https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/util.py#L45

**Comment by 1271** [comment]
You can also use the Info class
If you need any additional flags or features, I'll try to add them.

**Comment by tgaugry** [comment]
> You can also use the Info class

Yes, I saw that and edited my message. We likely have written simultaneously

> If you need any additional flags or features, I'll try to add them.

That's very kind of you. What i'm aiming is to use a db to store links and manga informations, and use it to regularly download updates. For that reason, i'm mostly interrested in the errors reporting and description features.

For now, i'm thinking:
- More content in Info class, like previously downloaded chapters list or conveninence function (ie `has_error`)
- A way to get the (currently internal) provider/download/archive errors. Some of them end up in the JSON summary, some of them are only logs
- A cleaner entrypoint; currently if inheriting `Cli` class, which feels kinda wrong.

If you are also interested and this can be included in the main branch, then i can develop these functionality as PR. Just checking beforehand, nothing worse than a "this code does not fit in this project" PR ^^

**Comment by 1271** [comment]
Initially, the project was not conceived as something that will live for more than a couple of days, and even more so I did not think that someone other than me would use it. Therefore, some code is done on the knee, "because it's easier this way."

> inheriting cli

You can write your own class to replace cli. This is how it was originally intended.

**Comment by 1271** [comment]
Once I have a little more time, I'll update the code for this issue.

**Comment by tgaugry** [comment]
That should do the trick. The error list field is quite ugly now. A cleaner way would be to maintain multiple list (missing, not images, etc). That may be overengineering...

**Comment by 1271** [comment]
Merged, thanks :D

**Comment by tgaugry** [comment]
Wow, that was quick XD. Didn't expect to pass without edits. Thanks !

In any case, I'm closing this issue, the remaining problem (images sometimes missing from the website) is not due to manga-py, but to the website.

Thanks again for your time !

**Comment by 1271** [comment]
I'll be glad to help. There will be one edit, but I'll figure it out myself. Thank you for your time. And thanks for using manga-py
