### ISSUE TITLE
Support for Python3.9

### ISSUE THREAD

**Issue by vmdude** [manga-py/manga-py#356]
# Bug report
As per https://pillow.readthedocs.io/en/latest/installation.html#python-support Python 3.9 support for Pillow start from version 8.0. But `manga-py` only support Pillow 7.x

https://github.com/manga-py/manga-py/blob/8f9abbfbfa068ef85b1b3e242af6b1154f3c5755/requirements.txt#L5

Description | Data
---|---
OS | MacOS Catalina 10.15.7
Python version | 3.9.0
Pip version | 20.2.4
Manga-py version | 1.24.2

#### To Reproduce:
1. Try to install `manga-py` with Python3.9, it will fail with error (same behavior with `pip install manga-py` or with `git clone` and `pip install -r requirements.txt`):
```text
The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.
```

#### Additional context
This issue is discussed in https://github.com/python-pillow/Pillow/issues/4956 and https://github.com/python-pillow/Pillow/issues/3438

**Comment by 1271** [comment]
Will be updated soon. Thanks for issue

- [x] Update base docker image
- [x] Update setup.py / requirements.txt
- [x] Update main docker image

**Comment by 1271** [comment]
Please, check version `1.25.0`

**Comment by vmdude** [comment]
It successfully work as expected with release `1.25.0`:

```bash
$ python --version
Python 3.9.0
$ pip install manga-py --upgrade --user
...
Successfully installed manga-py-1.25.0
$ manga-py --version
1.25.0
```
