### ISSUE TITLE
More granular download control

### ISSUE THREAD

**Issue by tgaugry** [manga-py/manga-py#360]
Not so much a feature request, just a question.

Short version: Why is there 2 different download implementations, `Http2` and the one embedded in `Provider` class ?

Long version:

I'm trying to get a better control on the chapter download, like downloading one chapter at a time or skipping the file system check of the archive and replacing it with a database check.

A simple way to do that would be to move almost all of the code (except the last line, `loop_chapters`) of the `process` method from provider class to a `prepare_downloads` method.
Then rewrite process as just a combination of these 2 methods. People can then call them separately, execute code in between, or execute a different download function.

However, this will not work with the providers that uses the `Http2` class, as specific code is executed in their `loop_chapters` method. A solution to this problem would be to refactor the download code in `Provider` class into a `HttpLegacy` or `HttpDefault` class, with the same methods name as the `Http2` class.

Before doing that though, I would like to know the reason of the 2 different classes, so i don't mess things up by accident :P

**Comment by 1271** [comment]
Hi. Some chapters are not downloaded when intermediate cookies are installed (default behavior for Provider).
In addition to this, the default behavior is to load images one at a time.
However, some sites allow you to download the entire archive of the chapter at once. (The main reason)

One day (hopefully) I will rewrite it all (v2) and get rid of this behavior.
But now it works like this.

**Comment by tgaugry** [comment]
Question was answered and code was merged. Thanks again, closing this issue.
