### ISSUE TITLE
Viz Shounen Jump downloads fail because of "sn't image"

### ISSUE THREAD

**Issue by ghost** [manga-py/manga-py#366]
# Bug report
Environment:

Description | Data
---|---
OS | macOS 11.2.1
Python version | 3.9.1
Pip version | 21.0.1
Manga-py version | 1.26.1
URL | https://www.viz.com/shonenjump/chapters/my-hero-academia

#### To Reproduce:
Run the following command to get the latest chapter (free):
``` bash
manga-py https://www.viz.com/shonenjump/chapters/my-hero-academia --reverse-download --max-volumes 1
```

#### Error
I get the following error messages
```
N/A% (0 of 250) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--"WARNING:/manga_py/base_classes/archive.py:56:2021-02-16 14:13:45,167:File "/var/folders/7y/bzfzj1nx5wb5npffzj76gq500000gn/T/.PyMangaDownloader/temp_6381/000_get_manga_url" isn't image"
"WARNING:/manga_py/base_classes/archive.py:56:2021-02-16 14:13:45,167:File "/var/folders/7y/bzfzj1nx5wb5npffzj76gq500000gn/T/.PyMangaDownloader/temp_6381/001_get_manga_url" isn't image"
  0% (1 of 250) |                        | Elapsed Time: 0:00:00 ETA:   0:02:35
...
```

Since it worked fine a week ago I guess Viz changed the API.

**Comment by 1271** [comment]
Thanks for issue.

As I understand it, version `pip install manga-py==1.25.0` is working?
You can install it temporarily.

I'll try to fix it soon

**Comment by ghost** [comment]
I didn't check before, but now that I did I can confirm that it works with version 1.25.0.

**Comment by 1271** [comment]
There were a lot changes in version 1.26 from #362
Something is probably not working as intended right now.

**Comment by tgaugry** [comment]
Currently looking at it !

**Comment by tgaugry** [comment]
Ok, problems comes from the `save_file`method (see https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/providers/viz_com.py#L208).
It's now always replaced by the stock one. replacing it with the one above "solves" the problem. I'll see if i can find a clean way to do that.

**Comment by 1271** [comment]
Thank you! After work I will definitely take a look.

**Comment by 1271** [comment]
@marvinpeter 
Please, check new version 
`pip install -U manga-py==1.26.2`

**Comment by ghost** [comment]
I just checked by running the same command I did in the bug report. Now I get a different error:
  7% (18 of 250) |#                      | Elapsed Time: 0:00:13 ETA:   0:03:13[TypeError('cannot unpack non-iterable NoneType object')]
I switched back to version 1.25.0 just to be sure it wasn't a mistake on my side and it worked with the old version.

**Comment by 1271** [comment]
Thanks! I will try to fix this.

**Comment by tgaugry** [comment]
Ok, I see the problem. It happen when it fail to download an image (due to network error/connection refused)... Not sure what is the expected behavior in thzat case ?

**Comment by 1271** [comment]
The image is skipped. The chapter is marked with _ERROR


A case with None is not processed. 

https://github.com/manga-py/manga-py/blob/2a2fa76a11fb29dbbef1ad5aa059190ed6c9a4e7/manga_py/providers/viz_com.py#L236-L239

https://github.com/manga-py/manga-py/blob/2a2fa76a11fb29dbbef1ad5aa059190ed6c9a4e7/manga_py/download_methods.py#L129-L133

**Comment by 1271** [comment]
Ok. Fixed in 1.26.3 (will be ready in the next hour)

**Comment by 1271** [comment]
@tgaugry Now this should definitely work :D  

`pip install -U manga-py==1.26.3`

P.S. Docker images also updated

**Comment by tgaugry** [comment]
Indeed, my bad ! Thank for your time !

**Comment by 1271** [comment]
No problem, it's okay. thanks for the help

**Comment by ghost** [comment]
I just checked again. Now it works as expected. Thanks.

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
