### ISSUE TITLE
Eror download from manga4life

### ISSUE THREAD

**Issue by aliabrar12** [manga-py/manga-py#372]
manga-py -W http://manga4life.com/manga/Solo-Leveling
"WARNING:\manga_py\parser.py:40:2021-03-12 02:09:07,680:Manga url changed! New url: https://manga4life.com/manga/Solo-Leveling"
"ERROR:\manga_py\download_methods.py:65:2021-03-12 02:09:11,044:Error processing file: vol_143-1"

**Comment by aliabrar12** [comment]
thanks brother

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
