### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by hello802** [manga-py/manga-py#373]
i don't know why but this error aspiring again.

(base) C:\Users\SURAVI>manga-py --max-volumes 5 https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/01/
Traceback (most recent call last):
  File "c:\users\suravi\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\suravi\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\SURAVI\anaconda3\Script...
         -> <code object <module> at 0x0000022E37C946F0, file "C:\Users\SURAVI\anaconda3\Scripts\manga-py.exe\__main__.py", line 2>
  File "C:\Users\SURAVI\anaconda3\Scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x0000022E3B487C18>
    -> <module 'sys' (built-in)>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\util.py", line 112, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x0000022E3B487AF8>
    -> <built-in function exit>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x0000022E3B4879D8>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(parse_args.__dict__, _info).start()
    |   |                    -> <manga_py.info.Info object at 0x0000022E3B48E608>
    |   -> Namespace(_raw_params='C:\\Users\\SURAVI\\anaconda3\\Scripts\\manga-py --max-volumes 5 https://hiperdex.com/manga/omniscient-rea...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 53, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x0000022E3B48E648>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\parser.py", line 52, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x0000022E3B48E488>
    |                     -> <manga_py.parser.Parser object at 0x0000022E3B48E488>
    -> <manga_py.parser.Parser object at 0x0000022E3B48E488>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\provider.py", line 86, in process
    self.prepare_download(url, params)
    |                     |    -> {'url': 'https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/01/', 'name': '', 'destination': 'Manga', 'no_progress': F...
    |                     -> 'https://hiperdex.com/manga/omniscient-readers-viewpoint-0403/01/'
    -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\provider.py", line 113, in prepare_download
    self.chapters = self._prepare_chapters(self.get_chapters())
    |               |                      -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
    |               -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
    -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\providers\hiperdex_com.py", line 9, in get_chapters
    manga_id = self.document_fromstring(self.content, '#manga-chapters-holder', 0).get('data-id')
               |                        -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
               -> <manga_py.providers.hiperdex_com.HiperDexCom object at 0x0000022E3B48E288>
  File "c:\users\suravi\anaconda3\lib\site-packages\manga_py\base_classes\static.py", line 24, in document_fromstring
    result = result[idx]
    |        |      -> 0
    |        -> []
    -> []
IndexError: list index out of range

**Comment by hello802** [comment]
did this bug fixed

**Comment by 1271** [comment]
Hi. Expect the next 24 hours. Thanks for waiting

**Comment by hello802** [comment]
Thank you for replying

**Comment by 1271** [comment]
The site uses cloudflare for protection. You must explicitly pass cookies to bypass.

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py

**Comment by hello802** [comment]
Ok thanks.
