### ISSUE TITLE
[Bug] Cannot download form AsuraScans

### ISSUE THREAD

**Issue by Middlepepper** [manga-py/manga-py#376]
When attempting to grab any manga from www.asurascans.com it fails with either "Provider not found" (look like this is due to a URL change?) or "IndexError: list index out of range"

Description | Data
---|---
OS | Dietpi v7.0.2
Python version | 3.7
Pip version | 21.0.1
Manga-py version | 1.29.1
URL | https://www.asurascans.com/comics/player-who-cant-level-up/

#### To Reproduce:
1. run manga-py https://www.asurascans.com/comics/player-who-cant-level-up/
2. Get error AttributeError: Provider not found

3. Change url to /manga/
4. run manga-py https://www.asurascans.com/manga/player-who-cant-level-up/
4. Get Error: IndexError: list index out of range

#### Additional context
Look like AsuraScans has change the url /Manga/ still lead to the page but all the links have /comics/

https://www.asurascans.com/comics/player-who-cant-level-up/ - link to manga page
https://www.asurascans.com/manga/player-who-cant-level-up/ - link to manga page
https://www.asurascans.com/solo-leveling-chapter-146/ - link to chapter

**Comment by Middlepepper** [comment]
Note sure if this would help for the URL issue but no idea regarding the index error
 
 File: manga-py/manga_py/providers/__init__.py /
 Line: 356
`    'mangasushi_net': [`
`      r'mangasushi\.net/manga/.',`
`      r'asurascans\.com/manga/.',`
`     r'asurascans\.com/comic/.',`
` ],`

**Comment by 1271** [comment]
> Note sure if this would help for the URL issue but no idea regarding the index error
> 
> `File: manga-py/manga_py/providers/__init__.py /`

Yes, the provider is chosen based on these regular expressions.

Thanks, I will update this today

**Comment by Middlepepper** [comment]
Thank you 1271 you are doing great work!

**Comment by 1271** [comment]
Thanks

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
