### ISSUE TITLE
[Bug] Leviatanscans - Provider not found.

### ISSUE THREAD

**Issue by Middlepepper** [manga-py/manga-py#380]
# Bug report
Environment (please complete the following information):

When trying to download from Leviatanscans the "AttributeError: Provider not found" error appears, the provider details appear to be in __init__.py

Description | Data
---|---
OS | Dietpi v7.0.2
Python version | 3.7
Pip version | 21.0.1
Manga-py version | 1.29.3
URL | https://leviatanscans.com/manga/trash-of-the-counts-family/

#### To Reproduce:
1. run manga-py https://leviatanscans.com/manga/trash-of-the-counts-family/
2. Get Error: IndexError: list index out of range

**Comment by 1271** [comment]
Please, check version 1.29.4

**Comment by Middlepepper** [comment]
Works as intended thanks 1271

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
