### ISSUE TITLE
[Bug] MangaKomi

### ISSUE THREAD

**Issue by Middlepepper** [manga-py/manga-py#383]
# Bug report
Environment:
When attempting to scrape manga from mangakomi.com. It look like there are two entries for Mangakomi in manga-py/manga_py/providers/__init__.py

The one under 'isekaiscan_com'

'isekaiscan_com': [
        r'isekaiscan\.com/manga/.',
        r'mangakomi\.com/manga/.',

and one of it's own.

 'mangakomi_com': [
        r'mangakomi\.com/manga/.',

Looks like the one on it's own is erroring out.

Description | Data
---|---
OS | Dietpi v7.0.2
Python version | 3.7
Pip version | 21.0.1
Manga-py version | 1.29.5
URL | https://mangakomi.com/manga/dead-tube/

#### To Reproduce:
1. Step 1 run manga-py https://mangakomi.com/manga/dead-tube/
2. Step 2 - Get the following error: [AttributeError("'NoneType' object has no attribute 'strip'")]

Steps to resolve
1. Step 1 - Run manga-py https://mangakomi.com/manga/dead-tube/  --force-provider http://isekaiscan.com/manga/_
2. Step 2 - Works without issue.

**Comment by Middlepepper** [comment]
@1271 Looks like this one is resolved
Input
`manga-py  --cbz -W -f -s 0 https://mangakomi.com/manga/dead-tube/ -N -n 'Dead Tube'`
Output
`Please, use --cookie and --user-agent options`
`No new chapters found`

**Comment by 1271** [comment]
The plugin that provided support for bypassing cloudflare protection is now paid.
Therefore, only manual installation of cookies is possible.
sorry
