### ISSUE TITLE
Request to add catmanga.org

### ISSUE THREAD

**Issue by Middlepepper** [manga-py/manga-py#401]
# Request to add catmanga.org

Looking at the reader it appears to be pretty straight forward.

The naming is /series/**MangaName**/chapters/1/001.jpg which could be .jpg or .png

Description | Data
---|---
**Url to add** | https://catmanga.org
**Chapter**| https://catmanga.org/series/tawawa/1
**Page Example** | https://images.catmanga.org/series/tawawa/chapters/1/001.jpg
**File Types** |  .jpg or .png

**Comment by 1271** [comment]
Will be coming soon. Thanks for the issue

**Comment by Middlepepper** [comment]
Confirmed working thanks!
