### ISSUE TITLE
genkan

### ISSUE THREAD

**Issue by inheritno** [manga-py/manga-py#402]
# Request to add a site

Description | Data
---|---
Url to add | genkan.io
Chapter    | https://genkan.io/manga/5200637380-ruler-of-the-land/chapters/3494
Page Example | https://proxy.genkan.io/?q=100&output=webp&errorredirect=https%3A%2F%2Fcdn.genkan.io%2Ffile%2Fgenkan-io%2Fmanga%2Fe35a64f4-3b2d-43d0-86ad-27c15c785af2%2Fchapters%2F77b91135-cdcb-431a-b242-2a1e6452a6b5%2F2.jpg&il=1&url=ssl%3Acdn.genkan.io%2Ffile%2Fgenkan-io%2Fmanga%2Fe35a64f4-3b2d-43d0-86ad-27c15c785af2%2Fchapters%2F77b91135-cdcb-431a-b242-2a1e6452a6b5%2F2.jpg

**Comment by 1271** [comment]
Will be ready soon. Thanks for the issue

**Comment by inheritno** [comment]
thank you
