### ISSUE TITLE
Add Requirements on Github repository page

### ISSUE THREAD

**Issue by Broeckelmann** [manga-py/manga-py#408]
# Bug report (not really a bug), sorry I don't know what to call this ._.
I don't if everyone has this at the beginning, but i had to `pip install image lxml` before I could you use manga-py would be nice if your would add a requirements section.

**Comment by 1271** [comment]
`lxml` is in the list of dependencies.
`image` is not required. 

https://github.com/manga-py/manga-py/blob/70aa046242d797506a6242c4638d2ca9d25ed9e6/requirements.txt#L3

**Comment by Broeckelmann** [comment]
Yeah but I mean before the installation steps, then users don't have to dig around and can start right of.

**Comment by 1271** [comment]
lxml is installed automatically when installing manga-py

**Comment by Broeckelmann** [comment]
okay strange had to install it by hand, hmm.

**Comment by Broeckelmann** [comment]
Maybe just my fault somehow then.

**Comment by Broeckelmann** [comment]
Not related but does it have config file support?

**Comment by 1271** [comment]
config file? Any example?

**Comment by 1271** [comment]
Do you mean to use a config file instead of arguments?

**Comment by Broeckelmann** [comment]
yeah something like in youtube-dl

**Comment by 1271** [comment]
Hmm... It's not hard to implement

**Comment by 1271** [comment]
OK no problem. To be added in next release: D

**Comment by Broeckelmann** [comment]
Would be really nice

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
