### ISSUE TITLE
'manga-py' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ghost** [manga-py/manga-py#417]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS |  Windows 10
Python version | 3.9.6
Pip version | 21.1.3
Manga-py version | 1.32.0
URL | 

#### To Reproduce:
1. Step 1
Open cmd
1. Step 2
Run manga-py
1. Step 3
Disappointment.

**Comment by 1271** [comment]
Try reinstalling manga-py
Not sure if I can help you with this error

**Comment by ghost** [comment]
Worked! Seriously why didn't i think of this lmao
