### ISSUE TITLE
Termux PIL pakage not found

### ISSUE THREAD

**Issue by Fmert24** [manga-py/manga-py#424]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Android 9 /Tetmux
Python version | 3.10.0
Pip version | 21.3.1
Manga-py version | 1.3.29.1

#### To Reproduce:
1. Step 1 pip install manga-py
1. Step 2 $manga-py

#### Additional context

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/manga-py", line 5, in <module>
    from manga_py.util import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/cli/__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/parser.py", line 6, in <module>
    from .provider import Provider
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/provider.py", line 10, in <module>
    from .base_classes import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/__init__.py", line 2, in <module>
    from .archive import Archive
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
ModuleNotFoundError: No module named 'PIL'

**Comment by 1271** [comment]
try this:

```bash
pip install Pillow
```

**Comment by 1271** [comment]
Better yet would be to update manga-py

```bash
pip install -U manga-py
```

**Comment by Fmert24** [comment]
> Better yet would be to update manga-py
> 
> ```shell
> pip install -U manga-py
> ```

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/manga-py", line 5, in <module>
    from manga_py.util import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/cli/__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/parser.py", line 6, in <module>
    from .provider import Provider
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/provider.py", line 10, in <module>
    from .base_classes import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/__init__.py", line 2, in <module>
    from .archive import Archive
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
ModuleNotFoundError: No module named 'PIL'

**Comment by 1271** [comment]
`pip install Pillow`

?

**Comment by Fmert24** [comment]
> `pip install Pillow`
> 
> ?

I instaled after manga-py 
It gave eroor agin so ı uninstaled and re instaled again

u0_a3160@localhost ~/.c/ranger> manga-py          Traceback (most recent call last):                  File "/data/data/com.termux/files/usr/bin/manga-py", line 5, in <module>
    from manga_py.util import main                  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments         File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/cli/__init__.py", line 11, in <module>                                      from manga_py.parser import Parser              File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/parser.py", line 6, in <module>
    from .provider import Provider
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/provider.py", line 10, in <module>
    from .base_classes import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/__init__.py", line 2, in <module>
    from .archive import Archive
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: dlopen failed: library "libzstd.so.1" not found

**Comment by 1271** [comment]
Please, check this: #48

Performance for android was never guaranteed, but it definitely worked

**Comment by Fmert24** [comment]
> `pip install Pillow`
> 
> ?
libzstd.so.1 neded so
I just googled and find this https://github.com/termux/termux-packages/issues/5073 
That artical was solved so ı just instaled pkg for libary

pkg install links                                             Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  brotli gdk-pixbuf libcairo libcroco liblzo
  libpixman librsvg libxft libxrender pango zstd
The following NEW packages will be installed:
  brotli gdk-pixbuf libcairo libcroco liblzo
  libpixman librsvg libxft libxrender links
  pango zstd
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 7360 kB of archives.
After this operation, 21.8 MB of additional disk space will be used.

And this is the new list of errors 
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/manga-py", line 5, in <module>
    from manga_py.util import main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/cli/__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/parser.py", line 6, in <module>
    from .provider import Provider
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/provider.py", line 10, in <module>
    from .base_classes import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/__init__.py", line 3, in <module>
    from .base import Base
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/manga_py/base_classes/base.py", line 5, in <module>
    from lxml.html import HtmlElement
ModuleNotFoundError: No module named 'lxml'

**Comment by 1271** [comment]
```
pip install -Ur cloudscraper cssselect lxml packaging 'Pillow~=8.1' progressbar pycryptodome PyExecJS requests better_exceptions pysocks
```

**Comment by 1271** [comment]
I don’t know why the modules were not installed automatically for you.

**Comment by Fmert24** [comment]
> I don’t know why the modules were not installed automatically for you.

I have no idea to maybe time for freshly instaled termux

**Comment by 1271** [comment]
Possibly (although pip does not matter which system the packages are installed on).
I have not tried installing manga-py on android. ))

**Comment by Fmert24** [comment]
pip install -Ur cloudscraper 'cssselect>=1.1' 'lxml~=4.6' 'packaging>=20.3' 'Pillow~=8.1' 'progressbar2>=3.50' 'pycryptodome>=3.9' 'PyExecJS>=1.5' 'requests>=2.23' 'better_exceptions>=0.2' 'pysocks>=1.7'               ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'cloudscraper'

But i instaled cloudscraper

**Comment by 1271** [comment]
Hmmmmm....
https://pypi.org/project/cloudscraper/

**Comment by 1271** [comment]
Oh...

**Comment by 1271** [comment]
I'm stupid...

Try this ( extra flag `-r` )

```
pip install -U cloudscraper cssselect lxml packaging 'Pillow~=8.1' progressbar pycryptodome PyExecJS requests better_exceptions pysocks
```

**Comment by Fmert24** [comment]
> I'm stupid...
> 
> Try this ( extra flag `-r` )
> 
> ```
> pip install -U cloudscraper cssselect lxml packaging 'Pillow~=8.1' progressbar pycryptodome PyExecJS requests better_exceptions pysocks
> ```

......
for full command output.                       ERROR: Command errored out with exit status 1:     command: /data/data/com.termux/files/usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-5m3t575i/lxml_bc1b7482598a4b3f9122a6773ca68b6b/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-5m3t575i/lxml_bc1b7482598a4b3f9122a6773ca68b6b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-_by4g5k0             cwd: /data/data/com.termux/files/usr/tmp/pip-install-5m3t575i/lxml_bc1b7482598a4b3f9122a6773ca68b6b/                                             Complete output (3 lines):                        Building lxml version 4.6.3.                      Building without Cython.                          Error: Please make sure the libxml2 and libxslt development packages are installed.

Cython?

**Comment by 1271** [comment]
system libraries again

**Comment by Fmert24** [comment]
> system libraries again

Facepalm again

**Comment by 1271** [comment]
https://pkgs.org/download/libxml2-dev
https://pkgs.org/download/libxslt-dev

**Comment by Fmert24** [comment]
> https://pkgs.org/download/libxml2-dev https://pkgs.org/download/libxslt-dev

.....ı m a newbe pls dont bully me when ı have no idea what to do whit library links...
wget?

**Comment by 1271** [comment]
pkg install libxml2-dev libxslt-dev

**Comment by Fmert24** [comment]
> 

.... well.....
pkg install libxml2-dev libxslt-dev                           Checking availability of current mirror: ok       Reading package lists... Done                     Building dependency tree... Done                  Reading state information... Done                 Package libxml2-dev is not available, but is referred to by another package.                        This may mean that the package is missing, has been obsoleted, or                                   is only available from another source             However the following packages replace it:          libxml2                                                                                           Package libxslt-dev is not available, but is referred to by another package.                        This may mean that the package is missing, has been obsoleted, or                                   is only available from another source             However the following packages replace it:          libxslt                                                                                           E: Package 'libxml2-dev' has no installation candidate                                              E: Package 'libxslt-dev' has no installation candidate

Time for instaling clang? For compiling from source ı guess

**Comment by 1271** [comment]
Yeah. First comment for #48 

`
pkg install clang libclang libclang-dev glib python-dev openssl-dev openssl-tool libcrypt libcrypt-dev libexpat glib-dev libexpat-dev libgc libgc-dev libxslt libxslt-dev pkg-config xmlsec-dev libjpeg-turbo libjpeg-turbo-dev binutils gdbm libandroid-support-dev libbz2 libffi libgcrypt libgpg-error libllvm libsqlite libutil libxml2 libxml2-dev ncurses-ui-libs ndk-stl ndk-sysroot pcre pcre-dev python xmlsec
`

**Comment by Fmert24** [comment]
> 

Well well well compiling probbly gona be as hard as instaling pakages from pip

Mı weel ı just try to trim error mesages ...yea

**Comment by Fmert24** [comment]
> Yeah. First comment for #48
> 
> `pkg install clang libclang libclang-dev glib python-dev openssl-dev openssl-tool libcrypt libcrypt-dev libexpat glib-dev libexpat-dev libgc libgc-dev libxslt libxslt-dev pkg-config xmlsec-dev libjpeg-turbo libjpeg-turbo-dev binutils gdbm libandroid-support-dev libbz2 libffi libgcrypt libgpg-error libllvm libsqlite libutil libxml2 libxml2-dev ncurses-ui-libs ndk-stl ndk-sysroot pcre pcre-dev python xmlsec`

python

Package xmlsec-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  xmlsec

E: Package 'libclang' has no installation candidate
E: Package 'libclang-dev' has no installation candidate
E: Package 'python-dev' has no installation candidate
E: Package 'openssl-dev' has no installation candidate
E: Package 'libcrypt-dev' has no installation candidate
E: Package 'glib-dev' has no installation candidate
E: Package 'libexpat-dev' has no installation candidate
E: Package 'libgc-dev' has no installation candidate
E: Package 'libxslt-dev' has no installation candidate
E: Package 'xmlsec-dev' has no installation candidate
E: Package 'libjpeg-turbo-dev' has no installation candidate
E: Package 'libandroid-support-dev' has no installation candidate
E: Unable to locate package libutil
E: Package 'libxml2-dev' has no installation candidate
E: Package 'ndk-stl' has no installation candidate
E: Package 'pcre-dev' has no installation candidate

**Comment by Fmert24** [comment]
> Yeah. First comment for #48
> 
> `pkg install clang libclang libclang-dev glib python-dev openssl-dev openssl-tool libcrypt libcrypt-dev libexpat glib-dev libexpat-dev libgc libgc-dev libxslt libxslt-dev pkg-config xmlsec-dev libjpeg-turbo libjpeg-turbo-dev binutils gdbm libandroid-support-dev libbz2 libffi libgcrypt libgpg-error libllvm libsqlite libutil libxml2 libxml2-dev ncurses-ui-libs ndk-stl ndk-sysroot pcre pcre-dev python xmlsec`

Nothing instaled

**Comment by 1271** [comment]
Oh...
 Unfortunately, I'm not sure if I can help (

**Comment by Fmert24** [comment]
> Oh... Unfortunately, I'm not sure if I can help (

Well ther is posibbly one option left and its find and compile the source code of each

Yep its gona be to trublesome so nope

**Comment by 1271** [comment]
Try looking for these packages for termux. Perhaps their prefixes have changed or something else. But the packages themselves should definitely be

**Comment by Fmert24** [comment]
> Oh... Unfortunately, I'm not sure if I can help (

Well ı will try to use manga-py on laptop then ....
I wonder how in the world that other termux user do this

**Comment by Fmert24** [comment]
> Try looking for these packages for termux. Perhaps their prefixes have changed or something else. But the packages themselves should definitely be

I remember those packages was there at least 3 or 4 of them but maybe they removed or there is another repo out there that contains them..

**Comment by 1271** [comment]
> another repo

Yes it is possible

P.S. 
termux left google play about six months ago. Maybe something changed then

**Comment by Fmert24** [comment]
> > another repo
> 
> Yes it is possible
> 
> P.S. termux left google play about six months ago. Maybe something changed then

well ı downloded manga-py to my laptop now and ı just get ModuleNotFoundError: No module named 'lxml' error so ı do what you wrote and manga-py perfectly working thx

**Comment by Fmert24** [comment]
Is this works as pillow 
https://github.com/uploadcare/pillow-simd
Or creates an error

**Comment by 1271** [comment]
For some reason, the installer (pip) thinks you already have these packages and doesn't install them (this is checked at install time)
The next release of manga-py will definitely require these packages. Sorry for this inconvenience

**Comment by z8512** [comment]
`pkg install libxml2 libxslt && pip3 install lxml`
Dev files are included in main package. There isn't separate dev, devel package in termux like libxml2-dev

**Comment by z8512** [comment]
Sorry @1271 developer, although you made this great app, we are disturbing you with small issue

**Comment by 1271** [comment]
> Sorry @1271 developer, although you made this great app, we are disturbing you with small issue

Don't worry, it's not difficult for me.
Also, sometimes it's really a manga-py problem.
