### ISSUE TITLE
Adding a Chocolatey Auto-Update Package (Windows)

### ISSUE THREAD

**Issue by BradKML** [manga-py/manga-py#425]
# Feature request

**Is your feature request related to a problem? Please describe.**
https://github.com/chocolatey-community/chocolatey-package-requests/issues/1011

**Describe the solution you'd like**
An installer package pipeline for Manga-Py

**Describe alternatives you've considered**
`pip` but that is mainly for programming and scripting purposes, not CLI software.

**Comment by 1271** [comment]
Oh, I think it can be arranged.
Winter holidays are ahead, so there will be a lot of time. There will be a lot to change in manga-py
I do not promise, but I think it will be done. Thanks for the issue

**Comment by jakublevy** [comment]
Windows builds: https://github.com/jakublevy/manga-py-win
Chocolatey package: https://community.chocolatey.org/packages/manga-py

**Comment by jakublevy** [comment]
It did not get through virus scanner on choco, so I changed pyinstaller to 4.5.1 and it is now on [2/66](https://www.virustotal.com/gui/file/dec6ccdda46d1ce1c3a04c173724e42b4afc717a68e01e55906194368bbf5b32) so now it should get through.

**Comment by 1271** [comment]
Thanks for your work

**Comment by jakublevy** [comment]
The reviewer finally checked the [package](https://community.chocolatey.org/packages/manga-py). As the message left indicates, the package will not get approved since it is not an official binary.

Could we just move my repo [jakublevy/manga-py-win](https://github.com/jakublevy/manga-py-win) to [manga-py/](https://github.com/manga-py) or could you (@1271) just provide Windows binary somewhere here?

Then we should hopefully get an approvement.

**Comment by 1271** [comment]
@jakublevy
Please accept an invite. I can make a repository for you.
And thanks for your work. :D

**Comment by 1271** [comment]
@jakublevy Thank you. Repository at your disposal

**Comment by jakublevy** [comment]
@1271 
thanks, for you swift response!
I was just writing message, that I could not push, thanks for commit access.

**Comment by jakublevy** [comment]
So I updated the package on Chocolatey, will let you know when I get a response/approvement from moderator.

**Comment by 1271** [comment]
Thank you anyway.

P.S.
If you need any more action from me, feel free to "ping" me in this issue or in a separate one, of your choice.

**Comment by jakublevy** [comment]
The package has been approved https://community.chocolatey.org/packages/manga-py

@1271 This issue can be closed now.

**Comment by 1271** [comment]
Thanks for help
