### ISSUE TITLE
Add Site Request

### ISSUE THREAD

**Issue by thestreetdj** [manga-py/manga-py#434]
# Request to add a site

I would like to request additional sites for Manatoki and JMana.

Description | Data
---|---
Url to add | http://manatoki125.net (The number changes whenever the domain is blocked)
Url to add | https://www.jmana1.net (The number changes whenever the domain is blocked)

**Comment by 1271** [comment]
Thanks for the issue. I will try to add it as soon as possible.

**Comment by 1271** [comment]
Check tag [1.33.2](https://github.com/manga-py/manga-py/releases/tag/1.33.2)

**Comment by z8512** [comment]
@thestreetdj please close the issue now

**Comment by 1271** [comment]
Hi @thestreetdj , I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
