### ISSUE TITLE
readmanga not work

### ISSUE THREAD

**Issue by Suydes** [manga-py/manga-py#435]
Такая фишка что раньше можно было качать мангу (ридманга если что сейчас под .io доменом) если просто заменить с readmanga.io на readmanga.live. Суть была в том что readmanga.live просто ссылался на readmanga.io и вот с недавнего времени теперь readmanga.live вообще не работает, и манга не качается вовсе естественно. Вам вроде достаточно сменить что бы все происходило не через .live, а через .io, буду ооочень благодарен за фикс

**Comment by 1271** [comment]
![изображение](https://user-images.githubusercontent.com/1452243/160769926-bfbc34e2-e81f-42bc-addc-951ab10b6e1c.png)

Можно пример, который не работает?

**Comment by 1271** [comment]
P.S. судя по всему, домен `readmanga.live` прекращает существовать. Можете использовать новый домен, всё должно работать.

Спасибо, что пользуетесь manga-py

Если у вас всё работает, пожалуйста пометьте проблему как решенную

**Comment by Suydes** [comment]
Дело в том что я использую эту либу в телеграм боте, и каким то образом именно там он не хочет взаимодействовать с ридмангой, пробнул просто с .io, но так и пишет что не доступно скачивание

**Comment by Suydes** [comment]
хм, а скачивать с remanga.org у вас получается?

**Comment by 1271** [comment]
> Дело в том что я использую эту либу в телеграм боте, и каким то образом именно там он не хочет взаимодействовать с ридмангой, пробнул просто с .io, но так и пишет что не доступно скачивание

Нужен пример ошибки

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
