### ISSUE TITLE
Naver Webtoon background music in chapters

### ISSUE THREAD

**Issue by bumbaras** [manga-py/manga-py#444]
I wonder if manga-py supports m4a audio files (i mean downloads them) when they are placed in episode?

**Comment by 1271** [comment]
No. And probably never will.

**Comment by bumbaras** [comment]
_images_helper(parser, '#_imageList img', 'data-url')
Which library is this from? I still know almost nothing about python including libraries.

I also just found out that webtoons app trolled me offering png with jpg extension which i treated with jpg fixer. Need to modify fixer again and fix those pngs ...
I was using webtoons app to download manhwa previously. Webtoons app decrease jpg quality to 70, instead of 90 offered on www.

Ok, audio is not given explicitly, its HLS and it seems it is encrypted somehow. Don't know easy way to fetch HLS stream. Seems the easiest way is to fetch it in android reader.

**Comment by 1271** [comment]
> Don't know easy way to fetch HLS stream

You can use for example youtube-dl to get HLS
Are you saying it's encrypted? Then you can leave this venture

---

> Which library is this from

Foy python you can use this: https://docs.python.org/3/library/html.parser.html

**Comment by 1271** [comment]
This is the case in most languages. Try type in google: "html parser &lt;language>"

**Comment by bumbaras** [comment]
Yep, it's aes-128 according to m3u8. "Native MPEG-dash plus HLS playback" firefox addon can play it and VLC media player can play it. The addon is a wrapper for two ready to use libs. This venture is hopeless for my current knowledge :).
Thread for close i think.
