### ISSUE TITLE
Cloudscrape

### ISSUE THREAD

**Issue by bumbaras** [manga-py/manga-py#445]
Hello. Did You plan to use cloudscrape? I see it in requirements but probably nothing elsewhere. I don't even know if cloudscrape is reliable these times as cloudflare bypass. I need to replace flareresolverr which no longer works on Win7. According to cloudscrape author replacing any `requests.` with `scrape.` should give perfect cloudscrape bypass but not sure about it ...

**Comment by 1271** [comment]
Have you tried using cloudscrape ?
Probably not.

> cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.
