### ISSUE TITLE
e-hentai limited to 40 pages per archive

### ISSUE THREAD

**Issue by w108x** [manga-py/manga-py#446]
Downloading from e-hentai.org, you can only download 40 pages per file, if it's over 40 pages it will create a second file.

See here:

https://e-hentai.org/g/2207734/8b819d05d5/

this hentai manga has 44 pages and it downloads it in 2 files.

**Comment by 1271** [comment]
Thanks. I will check it

**Comment by 1271** [comment]
Everything works correctly

**Comment by w108x** [comment]
Not for me, It only downloads 40 pages at a time for any manga and breaks them in multiple files. Expected behavior is to download all pages in one file.

\> manga-py --max-threads 1 --wait-after-page 1 -n "[Noumusai (Miyashiro Yousuke)] Mucchiri Dekachichi Dark Elf no Oba-san to Icha Love Fudeoroshi Seikatsu [English] [Digital]" https://e-hentai.org/g/2207734/8b819d05d5/

Please, wait...

100% (40 of 40) |#############################################################| Elapsed Time: 0:01:45 Time:  0:01:45
100% (4 of 4) |###############################################################| Elapsed Time: 0:02:32 Time:  0:02:32

\> dir

05/10/2022  11:32 AM        14,804,785 vol_000-0.cbz
05/10/2022  11:35 AM           689,103 vol_001-0.cbz

\> manga-py --version

1.33.2

\>python --version

Python 3.10.4

But same behavior with Python 3.9

**Comment by 1271** [comment]
> download all pages in one file

I saw a manga on this site that had about 300 pages. This is approximately 1200 files.
I'm not going to change behavior for you, sorry

**Comment by w108x** [comment]
what do you mean not change behavior for me? This is supposed to be one file, so the current behavior is either a bug or just bad. But it's your program so up to you, like this it's unusable.

**Comment by w108x** [comment]
It is one comic of 44 pages, and it should be one zip/cbz/etc. file. I don't understand what you mean 300 pages is 1200 files.

**Comment by 1271** [comment]
Images from one page are packed into a separate archive.
This is expected behavior.

I understand what you are talking about, but for some reason I will not pack all the images into one archive.

You may well pack them yourself.

**Comment by w108x** [comment]
Ah, gotcha, ok, btw is there a way to disable comicinfo generation?

**Comment by 1271** [comment]
Sure. You can run it without `--cbz` flag
