### ISSUE TITLE
How can I bypass IP Ban when using manga py?

### ISSUE THREAD

**Issue by ShuuGoya** [manga-py/manga-py#457]
I tried to download multiple Mangas from e-hentai.org but after around the 3rd im getting this message:

"Your IP address has been temporarily banned for excessive pageloads which indicates that you are using automated mirroring/harvesting software. The ban expires in 22 hours and 38 minutes"

How can I bypass this Issue?

My current options are:

manga-py [Link] --name '[Name]' -d [Directory] -z -N --wait-after-page 1 -t 1

**Comment by 1271** [comment]
just wait

In the future, you can try these options:

`--wait-after-page 5`
`--wait-after-chapter 30`

**Comment by ShuuGoya** [comment]
Ah so the Time between each Chapter and Page needs to be longer?

**Comment by 1271** [comment]
I think so.
These parameters make manga-py wait before trying to take the next action.

--max-threads (-t) also affect the speed of work, but only to get images.

Perhaps you should also sometimes pause between obtaining manga (be condescending to the site owner)

**Comment by ShuuGoya** [comment]
Nope I tried it from a different Network an it still gave me the IP Ban but this time after the 5th one.

**Comment by 1271** [comment]
Well, that's all I can guess. You can try to increase the values for waiting even more, for example
Not sure if I can help you
