### ISSUE TITLE
download to mount drives?

### ISSUE THREAD

**Issue by silentquiet** [manga-py/manga-py#463]
How can I allow docker manga-py to download to a mounted drive, I'm still new to docker but I was able to run docker manga-py successfully and download some manga to my /home/<user> directory as well as other directories within /home/<user>/, But I would really like it to download to /mnt/drive1/books but all my attempts are getting me "Permission denied". 

what I'm running in cli
docker run -it -v ${PWD}:/home/<user> mangadl/manga-py <URL> -d /mnt/drive1/books

Thanks in advance.

**Comment by 1271** [comment]
Hi. Check this https://docs.docker.com/storage/bind-mounts/

You can use `-v` for docker

**Comment by silentquiet** [comment]
thanks for your reply

Ok I tried the following in cli: 
1. docker run -it -v "${PWD}"/mnt/drive1/books:/home/[user] mangadl/manga-py [URL] 
This downloaded nothing but in my home folder/directory it created new folders instead
2. docker run -it -v "${PWD}"/mnt/drive1/books:/home/[user] mangadl/manga-py [URL] -d /mnt/drive1/books
still getting permission denied 
3. docker run -it -v /mnt/drive1/books mangadl/manga-py [URL] 
This downloaded nothing again it even showed the progress bar, no permission error
4. docker run -it  -v ${PWD}:/home/[user] mangadl/manga-py -d /home/[user]/manga
this is the only one that works but it downloads in the home/[user] folder and folders within [user] when using -d but I want it to download to the mounted drive

**Comment by 1271** [comment]
Try this:

`docker run -it -v /mnt/drive1/books:/home/[user] mangadl/manga-py [URL]`

This will create a `Manga` directory inside `/mnt/drive1/books` (i.e. /mnt/drive1/books/Manga)

Or:

`docker run -it -v /mnt/drive1/books:/tmp/mdl mangadl/manga-py -d /tmp/mdl/Manga [URL]`

will be the same result


P.S. The second option will not create additional files for you in the directory (configs)

**Comment by silentquiet** [comment]
Thank you the second option works nicely, I'm also thankful the fast response.
